### ISSUE TITLE
need simple freelist for gnix_fab_reqs

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#100]
We need a simple freelist (probably associated with the `gnix_domain_t` struct) to manage `gnix_fab_reqs`.   An initial set of may 100 elements could be added to the freelist, with additional
elements being allocated out of the heap.  This initial set size should ultimately be controllable using an `ops_open` method on the domain handle. 

This task needs to be completed as part of the solution for issue #5.

**Comment by ztiffany** [comment]
We're considering allocating a fabric request list per RDM endpoint.

**Comment by hppritcha** [comment]
Further consideration for multi-threaded usage of libfabric favors associating the `gnix_fab_req` free list with the EP.

**Comment by ztiffany** [comment]
Does this list have to be growable?  It looks like it's valid to limit the number of outstanding TXs to fi_info.tx_attr.size.

**Comment by hppritcha** [comment]
HI Zach,

Unfortunately this needs to be growable.  I looked at the ompi/ofi
libfabric component and it seems to assume that the provider can suck up
any
amount of send/recv/put/get requests.  The fab tests requests would have to
wait for a gnix_tx_descriptor before doing the GNI_SmsgSend, GNI_PostFma,
etc.  The gnix_tx_descriptor polls are indeed finite size, bound by the
size of the GNI CQ being used by the gnix_nic.

Howard

2015-04-21 9:09 GMT-06:00 ztiffany notifications@github.com:

**Comment by sungeunchoi** [comment]
@hppritcha 
`gnix_fab_req` has an EP field.  Is that what you want to use to identify it with an endpoint, or will that be redundant if the free list is associated with an EP?

**Comment by hppritcha** [comment]
i think we still need pointer to ep in the fab req. for other reasons.  but
if theres a pointer to the freelst in fab rew that can be removed.

---

sent from my smart phonr so no good type.

Howard

**Comment by sungeunchoi** [comment]
@hppritcha 
Is the field `active_fab_reqs` going to be tied to the `gnix_fab_req` free list?  In other words, should `active_fab_reqs` be incremented/decremented when a `gnix_fab_req` is removed from/returned to the list?

**Comment by hppritcha** [comment]
yes, I was thinking `active_fab_reqs` would be useful for things like a shmem_quiet on an ep.

**Comment by hppritcha** [comment]
in other words, another question for Steve V.

**Comment by hppritcha** [comment]
Sung, sorry but I don't think we can use slist for fabreqs.  Not sure what I was thinking.  We'll need to be able to remove elements from the list from arbitrary points in O(1),   So you'll need to use dlist.

**Comment by sungeunchoi** [comment]
I might be confused on what this list is used for.  I thought it was a simple free list.  Is the intention to use it for managing outstanding requests?  If so, I suggest we have a separate list for that.

**Comment by hppritcha** [comment]
oh you're right.  we will need to have "send" and "recv" fab reqs go on to slists for sending/receiving, and on a free list when available.

**Comment by sungeunchoi** [comment]
OK, so I'll do the freelist now, then add another issue for the send/recv lists.
