### ISSUE TITLE
need to document on GNI libfabric wiki page the OFED/libfabric release process

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#101]
We need a write up of how the libfabric code is going to be provided as part of the OFED release.  How will the gni provider be built in this release process?

**Comment by hppritcha** [comment]
@Pgrun 
@sungeunchoi 

Paul Sung and I are assigning this to you.

**Comment by Pgrun** [comment]
This slipped by unnoticed by me, 'til now.  First: libfabric isn't necessarily tied into any particular release of OFED,  libfabric has its own tarball and release mechanism.  As I understand it, OFED, whenever it releases, will simply pick up the latest libfabric stuff and include it.
Second; the current providers are included as part of libfabric and I would expect that to be the same for the gni provider.  Looking at the current directory structure on github, there is a directory called prov located directly beneath libfabric which contains the other four existing providers.  Any reason why we wouldn't simply move the gni provider there, whenever we're ready?

**Comment by sungeunchoi** [comment]
There will be no binary release of the GNI provider, and so this is a non-issue.
