### ISSUE TITLE
fi_atomic man page has both fi_atomicvalid and fi_atomic_valid

### ISSUE THREAD

**Issue by tonyzinger** [ofi-cray/libfabric-cray#1010]
In the name section, the api is fi_atomic_valid, fi_fetch_atomic_valid and fi_compare_atomic_valid.
In the synopsis section, the api is fi_atomicvalid, fii_fetch_atomicvalid and fi_compare_atomicvalid.

**Comment by hppritcha** [comment]
@tonyzinger I think this should be filed on the upstream issue list if you haven't already.

**Comment by sungeunchoi** [comment]
Please file on upstream.
