### ISSUE TITLE
need a domain ops method to set/get GNI RDMA credentials from libfabric consumer

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#1014]
There are a number of applications that would like to make use of DRC to acquire GNI cookie credentials in a more flexible way than is currently available using srun/aprun job launch.  Currently there is not a way for the application to supply a DRC acquired RDMA credentials to the GNI provider.

It should be straightforward to add a a new `dom_ops_val` which would allow setting/clearing the domain's rdma credentials (GNI cookie) value.  If the value had not been previously set, it should return one or the other (or perhaps both in a struct?) supplied via the alps lli interface.

@jshimek

**Comment by hppritcha** [comment]
@sdvormwa

**Comment by jswaro** [comment]
We should be careful about how we design this, because it may be used in more contexts than the GNI provider. There has been discussion about a generic abstraction for providing protection keys (cookies) to a domain that could be used between various providers.

**Comment by hppritcha** [comment]
This will be handled by auth keys approach in 1.5.  See #1232 .
