### ISSUE TITLE
GNI_Post*() failed: GNI_RC_INVALID_PARAM

### ISSUE THREAD

**Issue by tschuett** [ofi-cray/libfabric-cray#1033]
We finished porting our application to ``FI_EP_RDM`` with the sockets provider and are now moving to the GNI provider:
https://github.com/tschuett/flesnet/tree/fles_libfabric

Message passing basically worked from the first try. We just have to add retries for dropped messages. However, RMA completely fails.

A remote EP sends a message to a local EP with his ep name, mr key and baseptr:
https://github.com/tschuett/flesnet/blob/fles_libfabric/lib/fles_libfabric/ComputeNodeConnection.cpp#L279
There hasn`t been a connection between the two yet.
The local EP puts the ep name into the AV and stores the mr infos.
https://github.com/tschuett/flesnet/blob/fles_libfabric/lib/fles_libfabric/InputChannelSender.cpp#L484
In the next step, the local EP posts three RMA calls to the remote ep:
https://github.com/tschuett/flesnet/blob/fles_libfabric/lib/fles_libfabric/InputChannelConnection.cpp#L72
We get no events from the cq. There are just log messages:

``
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_ctrl:_gnix_vec_at():220<trace> 
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2029<info> Scheduled TX VC (0x2aab0c004a50)
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_data:_gnix_vc_dequeue_smsg():1776<trace> 
libfabric:gni:ep_data:__smsg_eager_msg_w_data():1732<trace> 
libfabric:gni:ep_data:__gnix_msg_copy_data_to_recv_addr():211<trace> 
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2226<info> Dequeued TX VC (0x2aab0c004a50)
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2029<info> Scheduled TX VC (0x2aab0c004a50)
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2226<info> Dequeued TX VC (0x2aab0c004a50)
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2029<info> Scheduled TX VC (0x2aab0c004a50)
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2226<info> Dequeued TX VC (0x2aab0c004a50)
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2029<info> Scheduled TX VC (0x2aab0c004a50)
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2226<info> Dequeued TX VC (0x2aab0c004a50)
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2029<info> Scheduled TX VC (0x2aab0c004a50)
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2283<trace> 
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():211<trace> 
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2226<info> Dequeued TX VC (0x2aab0c004a50)
libfabric:gni:ep_data:_gnix_rma_post_req():836<warn> GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2191<warn> Failed to push TX request 0x44274d0: Invalid argument
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2029<info> Scheduled TX VC (0x2aab0c004a50)
``

Is there any way for us to find the root cause? Any help is appreciated.

**Comment by tschuett** [comment]
@fsalem

**Comment by jswaro** [comment]
Can you provide a log file in its entirety? 

What version of the provider are you using? master, v1.4, v1.3?

**Comment by tschuett** [comment]
Sure. Note, that @fsalem put some output of his own into the file.
https://www.dropbox.com/s/xzrhml7kffahc17/0.input.out?dl=0

We are tracking the master of the ofiwg repository. It should be pretty current.

**Comment by jswaro** [comment]
There is surprisingly little data there, but I don't think this is a common case for us. 

So common cases for that particular error can originate from the user application in several forms. 
- EP isn't fully set up, or allocated (set up issue)
- The local or remote memory is not mapped (allocation or scoping issue)
- Length of TX is longer than the mapped memory region (tx.length > mr.length)

Do you ensure that the buffer is not freed or reused until after the libfabric completion event is received?

**Comment by tschuett** [comment]
- We call `fi_getname` on both EPs so that we can establish a connection.  I am quite confident that they are fully setup.
-  We initially targeted the Verbs provider which requires `FI_LOCAL_MR`. At startup and when estabilishing a connection, we register all memory. But we should check again.
- We will check this.

All malloc and `fi_mr_reg` calls happen before using a connection. Memory is only freed at the end of application. But again, we will check.

Thanks for your help. This provides us some areas, where we can verify our code.

**Comment by jswaro** [comment]
Not a problem. Let me know what you find and we'll continue to try and diagnose the issue. If you get stuck, I can attempt to provide some debug code for the provider that isn't in master, but that will require a recompile of the GNI provider on your end.

**Comment by tschuett** [comment]
If you don't mind pointing us at the debug code, that could accelerate our search. We already spent quite some on this issue. However, memory registration was not the focus yet.

**Comment by jswaro** [comment]
Checkout the branch here at https://github.com/jswaro/libfabric/tree/debug/1033-gni_rc_inval_param or just apply the diff: https://github.com/ofi-cray/libfabric-cray/compare/master...jswaro:debug/1033-gni_rc_inval_param.diff

The output from those debug functions should allow us to check on some basic values to eliminate any simple issues.

**Comment by hppritcha** [comment]
I don't like the looks of this:

```
struct BufferInfo
{
    uint64_t addr; ///< Target memory address
    uint32_t rkey; ///< Target remote access key
};
```

the GNI provider needs all 64 bits returned by `fi_mr_key`

**Comment by hppritcha** [comment]
I would think the compiler would complain about this assignment:

```
send_status_message_.info.desc.rkey = fi_mr_key(mr_desc_);
```

**Comment by jswaro** [comment]
Some providers may not use all the bits, but to remain portable between all providers, you should retain all of the bits. 

See the definition in https://github.com/ofi-cray/libfabric-cray/blob/master/include/rdma/fi_domain.h#L235
