### ISSUE TITLE
stricter compiler checking configury option

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#1040]
It would be nice to have an easy to remember configury option to crank up the warning level, etc. of the compiler when building libfabric.  Open MPI project has, for example, an --enable-picky configure option which turns on the following gnu compiler options:

```
-Wall -Wundef -Wno-long-long -Wsign-compare
-Wmissing-prototypes -Wstrict-prototypes
-Wcomment -pedantic
```

**Comment by sungeunchoi** [comment]
Should be an upstream issue.
