### ISSUE TITLE
Retrying to send a message

### ISSUE THREAD

**Issue by fsalem** [ofi-cray/libfabric-cray#1049]
When a node wants to send a message to another node, which may be not running yet at the beginning, the first node cannot retry sending the same message again when FI_COMPLETION flag is used with fi_sendmsg. This is normal because the data buffer should not be used until getting a completion event. But if the FI_INJECT flag is used, it gives an error with "invalid arguments". Furthermore, if the FI_INJECT_COMPLETE flag is used, it doesn't generate completion event and it doesn't send retying messages, however it should !.

**Comment by hppritcha** [comment]
Are you observing this behavior using the GNI provider?  Do you have a test that demonstrates the problem?

**Comment by fsalem** [comment]
Hi,

Yes, this behaviour using the GNI provider. This test case happens when a node tries to send a message to another node which is not up and running yet. Unlike Sockets provider, the sending operation will not give any errors. When the destination node becomes up and running, it will neither receive the sent message nor the retrying messages which are sent by the same source node. You can check the full project here [Fles_libfabric](https://github.com/tschuett/flesnet/tree/fles_libfabric). You can also check the initial send operation from [here ](https://github.com/tschuett/flesnet/blob/fles_libfabric/lib/fles_libfabric/InputChannelConnection.cpp#L466) and you can check the retrying part from [here](https://github.com/tschuett/flesnet/blob/fles_libfabric/lib/fles_libfabric/InputChannelSender.cpp#L176) and [here](https://github.com/tschuett/flesnet/blob/fles_libfabric/lib/fles_libfabric/InputChannelConnection.cpp#L473)

**Comment by sungeunchoi** [comment]
Can you provide info on exactly how to reproduce this?  A stand alone test case would be preferred, but if that's not possible, info on exactly how to configure and run a test using FLES.

**Comment by fsalem** [comment]
This bug can be produced by the following:
- 2 nodes will be used. The first node will start and send a message to the second node with FI_COMPLETION flag, while the second node will be delayed and it will start after few second.
- Once the second node is started, it will call fi_recv, however, it will not receive anything.
- The 1st node will not be able to send any further messages. 
- Instead of FI_COMPLETION flag, if FI_INJECT is used, an error will be thrown.

Hint: This case can be generated with a version from libfabric-cray before Nov. 15. I haven't tested it after that date.

**Comment by fsalem** [comment]
I want to close this issue for now because it should be solved by implementing FI_EP_MSG
