### ISSUE TITLE
MR cache leaking nic references

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#1056]
As we are adding more and more unit tests to the gnitest, we're starting to see a problem with cached memory registrations when using lazy memory deregistration.  The issue is that when a region is registered with a gnix_nic, a reference is taken on it.  This is all fine and good, but at application termination, when the app closes a gnix_dom, although the MR cache is flushed, relevant gnix_nic references are not decremented.

As it turns out, we've been getting lucky with the criterion tests because running in exclusive mode (or using alps with --network option), we have enough available GNI CQs that we don't detect this resource leak.  However, if we add enough unit tests that make memory registrations, we eventually will hit this problem.  There will no longer be sufficient GNI CQs and cdm attaches will fail.

Its easy to see this problem by putting in print statements for gnix_nic refs incremented/decremented and using the rdm_sr test.  This test in particular shows the issue.

**Comment by jswaro** [comment]
I'm not sure this has anything to do with the cache. I think this has more to do with how the tests are written. 

In the setup routine, 4 regions are registered, and in the teardown routines, only 2 of them are freed. 

In setup: rem_mr, loc_mr, iov_dest_buf_mr, and iov_src_buf_mr are registered.
In teardown: only rem_mr and loc_mr are deregistered.

When we decided to go with reference counting based deferred destruction, it was done to alleviate some of the ordering concerns that go with non-deferred methods. You'd need to destroy x, before y... so on and so forth., unless you were deferring destruction until the ref count hit zero.  However, if you don't release all of the objects associated with different object (memory registrations hold a reference to the nic they are registered on), then the nic will never be freed.

**Comment by jswaro** [comment]
As an alternative, you can write a 'gnix_release' function, and replace the gnix_ref_put calls in fi_close functions for our objects with this type of definition

```C
#define GNIX_RELEASE(obj) \
    do { \
        int references = gnix_ref_put(obj); \
        if (references != 0) GNIX_FATAL("something didn't release in the correct order"); \
    } while (0)
```

**Comment by chuckfossen** [comment]
The scalable tests also have the same issue as @jswaro noted since it was copied from the rdm_sr tests.

**Comment by hppritcha** [comment]
I think this issue can be closed now.
