### ISSUE TITLE
MSG EP should not rely on busy_spinning sread function

### ISSUE THREAD

**Issue by jshimek** [ofi-cray/libfabric-cray#1063]
The new FI_MSG system seems to rely on a busy spinning fi_cq_sread calling __gnix_eq_progress to make progress on its connections, this will not work with the wait_object system coming in with PR #1034, since that system fixes the busy spin and makes it a blocking wait call.

With #1034 on top of the fi_msg changes all the msg fabtests fail due to connection setup failures.
@sungeunchoi @ztiffany @hppritcha

**Comment by ztiffany** [comment]
Can you add EQs to a global list whenever they're created in gnix_eq_open?  Then iterate over that list and call progress on each EQ right after you progress the global NIC list in your wait progress thread?

**Comment by sungeunchoi** [comment]
This seems like a good symmetric solution, and not hard.  What are the downsides?

**Comment by jshimek** [comment]
I will add a global list of eq's when they are created based on zach's comment this will allow sread to function then the gnix_wait progress thread can iterate over the list getting connections setup. Since that seems to be the best solution at the current moment.
