### ISSUE TITLE
Unaligned fi_read() never completes when length is < 8192 bytes 

### ISSUE THREAD

**Issue by epaulson10** [ofi-cray/libfabric-cray#1066]
I am trying to wrap up the changes needed to get the gni provider working for the OFI GASNet conduit. I am seeing a couple of tests that hang forever however. One of them is GASNet's testslice, which performs a bunch of randomized memory transfers. What I am seeing is that when the transfer size is less than 8192 bytes and is unaligned, fi_read() never generates a completion. Here are some relevant log messages (the final few lines repeat forever until I interrupt the program):

```
libfabric:gni:ep_data:_gnix_rma():937<info> [11733:1] Using CT for unaligned GET, req: 0x8a6128
libfabric:gni:mr:gnix_mr_reg():180<trace> [11733:1]
libfabric:gni:mr:_gnix_mr_cache_register():1527<trace> [11733:1]
libfabric:gni:mr:__mr_cache_search_inuse():1205<debug> [11733:1] found a key that matches the search criteria, found=2aab4bd04000:2fb000 key=2aab4bf27000:2000
libfabric:gni:mr:__mr_cache_search_inuse():1216<debug> [11733:1] found an entry that subsumes the request, existing=2aab4bd04000:2fb000 key=2aab4bf27000:2000
libfabric:gni:mr:__mr_cache_entry_get():852<trace> [11733:1]
libfabric:gni:core:gnix_mr_reg():246<debug> [11733:1] 0x8a5830 refs 16
libfabric:gni:core:gnix_mr_reg():247<debug> [11733:1] 0x8c6968 refs 12
libfabric:gni:ep_data:_gnix_rma():964<info> [11733:1] auto-reg MR: 0x939900
libfabric:gni:ep_data:_gnix_rma():999<debug> [11733:1] Queuing (0x2aab4bf27d16 0x2aab4bf4bbb9 3799)
libfabric:gni:ep_data:gnix_ops_allowed():817<debug> [11733:1] flags:0x8080000011000104, FI_RMA, FI_READ, FI_COMPLETION, FI_DELIVERY_COMPLETE
libfabric:gni:ep_data:gnix_ops_allowed():819<debug> [11733:1] peer_caps:0x4, FI_RMA
libfabric:gni:ep_data:gnix_ops_allowed():821<debug> [11733:1] caps:0x4, FI_RMA
libfabric:gni:ep_data:__gnix_rma_fill_pd_chained_get():513<info> [11733:1] ct_rem_addr[0] = 0x2aab4bf4bbb8 0x2aaaacbf0010, ct_rem_addr[1] = (nil) (nil)
libfabric:gni:ep_data:_gnix_rma_post_req():833<warn> [11733:1] GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:_gnix_vc_queue_tx_req():2092<debug> [11733:1] Queued request (0x8a6128) on full VC
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2043<info> [11733:1] Scheduled TX VC (0x8ce0e8)
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2240<info> [11733:1] Dequeued TX VC (0x8ce0e8)
libfabric:gni:ep_data:gnix_ops_allowed():817<debug> [11733:1] flags:0x8080000011000104, FI_RMA, FI_READ, FI_COMPLETION, FI_DELIVERY_COMPLETE
libfabric:gni:ep_data:gnix_ops_allowed():819<debug> [11733:1] peer_caps:0x4, FI_RMA
libfabric:gni:ep_data:gnix_ops_allowed():821<debug> [11733:1] caps:0x4, FI_RMA
libfabric:gni:ep_data:__gnix_rma_fill_pd_chained_get():513<info> [11733:1] ct_rem_addr[0] = 0x2aab4bf4bbb8 0x2aaaacbf0010, ct_rem_addr[1] = (nil) (nil)
libfabric:gni:ep_data:_gnix_rma_post_req():833<warn> [11733:1] GNI_Post*() failed: GNI_RC_INVALID_PARAM
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2193<debug> [11733:1] Failed to push TX request 0x8a6128: Invalid argument
libfabric:gni:ep_data:__gnix_vc_push_tx_reqs():2205<warn> [11733:1] Failed to push TX request 0x8a6128: Invalid argument
libfabric:gni:ep_ctrl:_gnix_vc_tx_schedule():2043<info> [11733:1] Scheduled TX VC (0x8ce0e8)
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_tx_vc():2240<info> [11733:1] Dequeued TX VC (0x8ce0e8)
```

I did some digging to see if I could figure out what was going on. The 8192 bytes threshold seems to be due to a different work_fn being chosen for the request if the size of the requests exceeds some threshold, and the default is 8192 bytes (I am looking at the _gnix_rma() function in gnix_rma.c). The provider is using chained transfers when the failure occurs. I am using the latest tip of the master branch in the upstream and running this on the NERSC Edison machine.

I haven't yet investigated the other failure, although I have reason to suspect it is the same root cause.

**Comment by sungeunchoi** [comment]
Are you able to give us a small test case to reproduce this?  Our unit tests do not exhibit this behavior.

**Comment by epaulson10** [comment]
Here is a reproducer. Change it from .txt to .c and compile with gcc -I\<Your include path\> -L\<Your lib path\> -lfabric gni_repro.c. -o gni_repro. The meat of the test starts on line 151.
[gni_repro.txt](https://github.com/ofi-cray/libfabric-cray/files/622888/gni_repro.txt)

This is a client/server program that runs on exactly two nodes. To use it do:
[node0] $ ./gni_repro
[node1] $ ./gni_repro node0

This reproducer allocates buffer of size BUFF_SIZE (initially set to 8192) for each node. Then the client does the following for 100 iterations:

- Pick a random location in the server's buffer
- Issue an fi_read() to read everything from that location to the end of the buffer.
- Poll the cq for the read completion
  - If the cq is polled 1,000,000 times, print a message and exit, because we hit the bug.

Running the program as is, it will fail every single time on iteration 0. If you increase BUFF_SIZE, say to 16k, you will see the program begins to exhibit non-determinism in where it fails (and you may get lucky and it will never fail if BUFF_SIZE is big).

Again, I tested this reproducer out on Edison and saw the same log messages being spit out from the provider.

**Comment by epaulson10** [comment]
@sungeunchoi Have you guys seen this? It's okay if you don't have time to look at it yet, I just want to make sure you have seen that I left a reproducer here.

**Comment by sungeunchoi** [comment]
I *think* #1083 may have fixed this problem.  I was able to run your test program and it exited without failure.  Can you double check with a more recent build that includes 48cd578?

**Comment by epaulson10** [comment]
@sungeunchoi Yes this did fix the issue. I look forward to seeing this commit in the upstream. Closing this issue now.
