### ISSUE TITLE
FI_MORE doesn't work with FI_FENCE

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#1074]
Right now, an FI_FENCE transaction can be placed on a more list.  FI_FENCE is handled inside _gnix_vc_queue_tx_req().  Putting a FI_FENCE req in a more list will break that implementation.

@a-abraham @sungeunchoi

**Comment by a-abraham** [comment]
For the moment, should we explicitly disallow FI_FENCE transactions from being added to the fi_more lists?

**Comment by ztiffany** [comment]
I think that would only be a partial fix.  That might not be worth it.
