### ISSUE TITLE
Move intermediate buffer from txd to fab_req

### ISSUE THREAD

**Issue by a-abraham** [ofi-cray/libfabric-cray#1077]
For chained_gets there is currently an intermediate buffer on a txd to be used for storing unaligned head/tail data.

FI_MORE will create a chain transaction of gets, and each individual request may require an intermediate buffer. To accommodate future work, the int_buf should be moved from txds to fab_reqs so that each request could properly handle data from unaligned gets. 

@ztiffany @sungeunchoi

**Comment by a-abraham** [comment]
Due to ofi-cray/libfabric-cray#1087  - rather than moving the int_buf from the TXD to the fab_req,  we can simply utilize the htd_buf that is available on the fab_req.

**Comment by sungeunchoi** [comment]
Closed by #1090
