### ISSUE TITLE
NIC ref counting/race issues in MR code

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#1086]
1. gnix_nic_alloc in gnix_mr.c adds a references on the newly created NIC that would never be removed.
2. list of NICs is traversed in __gnix_generic_register in gnix_mr.c while the list is not protected from changes and no references are held on any NICs in the list.

**Comment by jswaro** [comment]
> gnix_nic_alloc in gnix_mr.c adds a references on the newly created NIC that would never be removed

Please elaborate on your reasoning for this statement. What reference, taken where? 

> list of NICs is traversed in __gnix_generic_register in gnix_mr.c while the list is not protected from changes and no references are held on any NICs in the list

This is a general issue with the NIC list code. See gnix_nic_alloc, and __gnix_dom_ops_set_val. 

Each of these functions needs to wrap the loops in a lock: 
gnix_nic_alloc
__gnix_dom_ops_set_val
__gnix_generic_register

See gnix.h:380.
> 	/* list nics this domain is attached to, TODO: thread safety */

**Comment by ztiffany** [comment]
gnix_nic_alloc will leave a newly allocated NIC with a ref count.  gnix_mr.c will call nic_alloc if no NIC is yet allocated for a domain.  The ref count for the allocator is never removed in this case.

**Comment by jswaro** [comment]
I thought that may have been what you were referring to. I'll post a fix for it.

**Comment by jswaro** [comment]
I believe the NIC list code issues need to be handled separately as part of the comment with gnix.h:380.
