### ISSUE TITLE
FI_REMOTE_CQ_DATA does not work with FI_MORE

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#1110]
We need to disable chaining requests with FI_MORE if FI_REMOTE_CQ_DATA is used.  

The FI_REMOTE_CQ_DATA request flag indicates that a transaction should be accompanied with a remote CQ event.  That event is not delivered by the current FI_MORE chaining implementation.  At a minimum, we need to prevent a request from being chained with FI_MORE when  remote CQ data is requested so we are to spec.

**Comment by ztiffany** [comment]
We need to disallow FI_REMOTE_CQ_DATA for reads also.  That might be fixed just by removing FI_REMOTE_CQ_DATA from GNIX_READMSG_FLAGS.

**Comment by a-abraham** [comment]
I'll spin off a separate issue in response to your second comment. https://github.com/ofi-cray/libfabric-cray/issues/1131
