### ISSUE TITLE
Need to fill in cq_cnt and ep_cnt in endpoint attributes returned from fi_getinfo

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1128]

**Comment by sungeunchoi** [comment]
- cq_cnt can follow what we did for cntr_cnt
- What should we do with ep_cnt?  Should we use total number of gni cqs?  42?

**Comment by sungeunchoi** [comment]
@ztiffany Are there limits for FI_EP_MSG type on number of endpoints?  In particular, we have concerns about any limitation in the connection management stuff?

For other ep types, seem like SIZE_MAX is as good a value as any.

**Comment by ztiffany** [comment]
I don't think we have a limit on the number of endpoints, FI_EP_MSG or not.

Do we have a limit on libfabric counters?  I'm not sure we need one.

**Comment by jshimek** [comment]
Barring any changes from the discussion here I'll push up a mod and open a PR with the following:
Setting cq_cnt to equal cq_limit /2.
Setting ep_cnt to equal SIZE_MAX.

**Comment by sungeunchoi** [comment]
@chuckfossen @hppritcha Didn't we talk about ep limits with the SEP work?
