### ISSUE TITLE
Support the attr parameter passed to fi_tx(rx)_context

### ISSUE THREAD

**Issue by chuckfossen** [ofi-cray/libfabric-cray#1133]
Do we need to support different op_flags for TX vs. RX context?

**Comment by sungeunchoi** [comment]
I think @agontarek would say yes, and I would probably use it in that way also.

**Comment by chuckfossen** [comment]
@hppritcha, should the sep.info.fi_tx_attr/fi_rx_attr be returned here?
Do we need to separate the endpoint op_flags into Rx and Tx op_flags?

**Comment by hppritcha** [comment]
yes I think we need to keep the info in a way that you can return different values for ```fi_rx_context``` and ```fi_tx_context```
