### ISSUE TITLE
Tracker: Provider-specific issues from ABI-1.1 Update

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#1135]
- [x] ofiwg/libfabric#2618 #1147 #1223 
- [x] ofiwg/libfabric#2620 #1169 #1225 
- [x] ofiwg/libfabric#2621 #1170 
- [x] ofiwg/libfabric#2622 #1180 
- [x] ofiwg/libfabric#2623 #1189 
- [x] ofiwg/libfabric#2624 #1151 
- [x] ofiwg/libfabric#2625 #1166
- [x] ofiwg/libfabric#2626 #1152 
- [x] ofiwg/libfabric#2627 (ofiwg/libfabric#2732)
- [x] ofiwg/libfabric#2628
- [x] ofiwg/libfabric#2629 #1232

**Comment by jswaro** [comment]
2629 (auth key): We'll need ofiwg/libfabric#2632 to be complete first so that we can associate the memory region with the correct communication domain. 
2626: We'll need to add FI_LOCAL_COMM and FI_REMOTE_COMM to the domain modes of domains we allocate.
2625: We should be able to implement that easily.
2624: We can set this to 1 initially, then modify it to another value when fi_mr_regv is implemented in our provider later. 
2623: We *should* be able to support this trivially. It seems more of a parsing problem and we need to observe our current restrictions (FI_ADDR_GNI only)
2621: We *should* be able to support this trivially. It seems that we could abort easily on insert failure, then compare with the internal table when the sync call comes back in. 
2620: We can easily support this, but the documentation asks for an *optimal* value to be reported. I think we can easily report a maximum but it would be difficult to know what an optimal value would be.
2618: We *should* be able to support this trivially. This should require a modification to readfrom to return the fi_addr_t associated with the endpoint, which is stored as a gni level source address. We can either look up the fi addr or reconstitute it from the stored gni address.

**Comment by jswaro** [comment]
For 2626, we'll need to add FI_LOCAL_COMM and FI_REMOTE_COMM to the domain modes of domains we allocate.

**Comment by jswaro** [comment]
For 2625, we should be able to implement that easily.

**Comment by jswaro** [comment]
2624: We can set this to 1 initially, then modify it to another value when fi_mr_regv is implemented in our provider later.

**Comment by jswaro** [comment]
@sungeunchoi Thoughts?

**Comment by sungeunchoi** [comment]
Re: 2620, I commented in the original commit about a "don't care" value and was blown off.  Why would coming up with a max value be easy?  Isn't it arbitrary?  Also, I don't understand 1:1 comment.  Which CQs?  libfabric or ugni?

**Comment by jswaro** [comment]
For us, I think we could represent a maximum as 0-1 or the UINT maximum, meaning we could support as many as they want. 

**Yes**, I think it is arbitrary. We could set this to whatever we want essentially. 

My 1-to-1 comment is a possible guideline for advising what might be a natural mapping of counters to libfabric CQs.

**Comment by sungeunchoi** [comment]
Why is 1:1 a natural mapping?

**Comment by jswaro** [comment]
Disregard the 1-to-1 comment. 

After a bit more thought and looking into the code, we could have as many as 6 distinct counters per EP. My mistake as I thought they were bound to CQs.

**Comment by hppritcha** [comment]
Thanks for putting these together in one issue.  Very helpful.

**Comment by sungeunchoi** [comment]
Ranked 1-3 1==easiest, 3==hardest:

- 2618: (1)
- 2620: (2) maybe return max number of CQs (see also #1128)
- 2621: (2)
- 2622: (2) better understand this (might be a no op)
- 2623: (1)
- 2624: (1)
- 2625: (1)
- 2626: Only support FI_REMOTE_COMM (1)
- 2627: (1) we will not support multicast operations
- 2628: (2) wait on other providers
- 2629: (3) Jim tracking

**Comment by hppritcha** [comment]
related to #1147

**Comment by jswaro** [comment]
For 2629, the auth key work for memory registration has been committed to master. We can support the auth key work as soon as we devise a intermediate layer for nics/memory registrations within a domain associated with a given auth key

**Comment by chuckfossen** [comment]
I noticed #2627 is checked off. It looks like we should at least inialize the fi_ops_cm.join to a function that returns -FI_ENOSYS.

**Comment by jswaro** [comment]
Adding #1217
