### ISSUE TITLE
ABI-1.1 Add mode bit to relax completion flag reporting

### ISSUE THREAD

**Issue by e-harvey** [ofi-cray/libfabric-cray#1180]
See ofiwg/libfabric#2622 for more details.

**Comment by e-harvey** [comment]
The motivation for supporting this comes from ofiwg/libfabric#1142. Within the gni provider, CQ events are added in five places: 1 for send completions in `gnix_atomic.c`, 2 more for send/recv completions in `gnix_msg.c`, and 2 more for send/recv completions in `gnix_rma.c`. All of these places call `_gnix_cq_add_event` and set the completion flags by using bit masking. As far as I can tell non of the functions calling `_gnix_cq_add_event` require branching that could be eliminated by checking for the `FI_NOTIFY_FLAGS_ONLY` mode bit.

@sungeun @hppritcha So, would it be best to simply update `_gnix_cq_add_event` to check the flags parameter for `FI_NOTIFY_FLAGS_ONLY` and "When [this flag is] set on an EP, [ensure that] only the following flags are returned in completions:

FI_REMOTE_READ | FI_RMA (if FI_RMA_EVENT cap set)
FI_REMOTE_WRITE | FI_RMA (if FI_RMA_EVENT cap set)
FI_REMOTE_CQ_DATA
FI_MULTI_RECV"?

**Comment by hppritcha** [comment]
I think this would suffice to support ```FI_NOTIFY_FLAGS_ONLY.```
