### ISSUE TITLE
retrans tests do not release resources until end-of-test

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#1193]
Without reading the CQ errors in the retrans tests, the test will hold onto resources indefinitely until end-of-test when resources are forcibly released.

This affects resource bound modes such as MDD sharing off, or FI_MR_SCALABLE. The tests should be modified to read the CQ error so that the resources are released naturally.

@chuckfossen

**Comment by sungeunchoi** [comment]
Fixed in MR scalable work #1213
