### ISSUE TITLE
FI_REMOTE_WRITE needed even when only using as source buffer

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1197]
The FI_REMOTE_WRITE flag is needed when registering memory for the source side buffer of an fi_write operation.  According to the man page, this should not be necessary.

Should check if this is also the case for FI_REMOTE_READ.

**Comment by tonyzinger** [comment]
In my test program when using the gni provider, I need to have FI_REMOTE_WRITE flag when I am registering my source buffer for both a fi_write and fi_read operation for this test to execute successfully.  The sockets provider does not need the FI_REMOTE_WRITE flag.
