### ISSUE TITLE
rdm_mbw_mr benchmark hangs when using XPMEM for SEND_RECVV pattern

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#1215]
@e-harvey noticed that the rdm_mbw_mr benchmark hangs when run on a single node.
The problem is with xpmem based transfers where the send buffer is contiguous, but the receive
buffer is not.  The problem appears to be related to the progress thread as turning off auto-progess for data by adding
```
hints->domain_attr->data_progress = FI_PROGRESS_MANUAL;
```
when opening the fabric causes the problem to vanish.

**Comment by hppritcha** [comment]
Okay, looks like we need to be more careful on the receive side if iov_cnt > 1 on the receive side.

**Comment by e-harvey** [comment]
I'm unable to reproduce this hang on Trinitite ever since the 5 day DST from 3/6 - 3/10. Was XPMEM updated during the DST?

**Comment by hppritcha** [comment]
no probably not.  its a real bug.  its a resource leak that maybe you aren't hitting now.
