### ISSUE TITLE
need to improve checking of GNI provider attributes against app supplied fi_hints

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#1222]
GNI provider could be better at verifying GNI provider attributes are sufficient for any requested limits by the application via ```fi_getinfo```.  

As an example, GNI provider is not currently verifying ```cntr_cnt``` supplied by app vs what GNI provider supports.

Also impacted:
#1153   mr_iov_cnt enforcement

**Comment by sungeunchoi** [comment]
Closed by #770
