### ISSUE TITLE
Special case argument handling for FI_VERSION in check_cntr

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#1225]
See #1221 #1135

**Comment by chuckfossen** [comment]
Since this is grouped with #1169 in #1135, I assume this means to not check the cntr_cnt value when running with an API version < 1.5. This is currently only done in gnitest which was added at the same time the cntr_cnt was added. Seems like a nop to me.

**Comment by jshimek** [comment]
I am going to close this as ofi_check_domain_attrs which is called by _gnix_ep_getinfo already has special case handling for 1.5 where it only checks the cntr_cnt attribute if running against 1.5 or later.
