### ISSUE TITLE
Special case argument handling for FI_VERSION with mr_iov_limit

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#1226]
See #1221 #1135

**Comment by chuckfossen** [comment]
Depends on ofiwg/libfabric#2772.

**Comment by jshimek** [comment]
This looks to be covered by commit https://github.com/ofiwg/libfabric/commit/47bee5aadf77e876536adf48fd151d104acad60b 
Not sure if there is something extra to be done here.

@sungeunchoi
