### ISSUE TITLE
Runtime check for FI_VERSION with fi_mr_refresh 

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#1230]
See #1221 #1135

**Comment by sungeunchoi** [comment]
-FI_ENOTSUPP or -FI_ENOSYS?

**Comment by jshimek** [comment]
Giving to @jswaro as this is covered by issue #1217 and as such the check will be part of that work.

**Comment by jswaro** [comment]
closing as invalid. The functional requirements for FI_MR_REFRESH require FI_MR_SCALABLE, and FI_MR_SCALABLE is not selectable prior to 1.5. As it stands with the current scalable memory registration PR, it will return -FI_EINVAL if refresh is attempted with basic memory registration, since refresh is not supported in that mode.
