### ISSUE TITLE
Disable verbs provider by default on Cray XC

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1234]
Required for CLE6.X.

**Comment by hppritcha** [comment]
I don't see a way to do this without injecting configury changes in to the top level configure.ac.  I'm pretty sure folks would balk.  Cray did too good a job with CCM.  There are too many header files and libraries for ibverbs being installed on cray CLE6.x systems to support CCM to disable verbs easily.  There are no sentinels in any of these ibverbs related packages to distinguish a stock IB cluster install of the packages from a Cray CLE6.  Cray would need to add some kind of sentinel into at least one of these packages to allow for disabling of verbs within the libfabric configury.
