### ISSUE TITLE
Make FI_MR_SCALABLE key selection easier for clients

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1244]
MDD blocks are shared amongst all the processes on a node using a single ptag, so without assistance from the provider, clients will have to some how coordinate their keys and ranges of keys.

**Comment by sungeunchoi** [comment]
One possible solution would be to add a rank or some identifying info in the ep_name.

**Comment by jswaro** [comment]
The only thing we can do is provide a shared memory region accessible between processes on the same node. Clients will still need to coordinate key usage between nodes. I'll incorporate the design into the mr scalable work.
