### ISSUE TITLE
Add CQ IRQ masking infrastructure for progress engine

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#125]
The GNI provider auto progress implementation will create a progress thread which blocks waiting for CQ events.  The GNI provider should keep a count of the number of users entering and exiting the interface.  When a process first enters the provider, CQ interrupts should be masked with the GNI_CqInterruptMask() interface, preventing progress threads from being waken and avoiding contention between progress thread and application process while processing events.  When the last process exits the provider, CQ interrupts should be unmasked to allow the progress thread to detect future CQ events.  Performance of this feature may rely on fixes to the GNI_CqInterruptMask/Unmask interfaces in CLE 5.2UP04 or later.

**Comment by ztiffany** [comment]
@hppritcha are we thinking 1 progress thread/gnix_nic?

**Comment by hppritcha** [comment]
I think we have to unless `GNI_CqVectorMonitor` can handle monitoring CQs associated with multiple different nic handls.  If that's the case, we might not need more than a single progress thread/domain.
I'm still going to do the one pthread per `gni_cm_nic` as the `GNI_PostDataProbeById` can only handle on nic handle at a time.

**Comment by sungeunchoi** [comment]
Requires #235

**Comment by sungeunchoi** [comment]
Initial investigations showed that this did not help much.  Closing for now.
