### ISSUE TITLE
FI_SHUTDOWN on both sides

### ISSUE THREAD

**Issue by fsalem** [ofi-cray/libfabric-cray#1288]
Currently, FI_SHUTDOWN signal is received only in the local EQ but not the remote one. However, and according to the MAN page, both sides should receive the signal when fi_shutdown is called without one of the two EPs.

[This poll request "Implement reject, shutdown, EQ fixes"](https://github.com/ofi-cray/libfabric-cray/pull/1085) initiated a [stub code](https://github.com/ofi-cray/libfabric-cray/blob/master/prov/gni/src/gnix_cm.c#L887) for fi_shutdown but only one EQ will receive the FI_SHUTDOWN signal.

**Comment by ztiffany** [comment]
Our fi_shutdown() implement is not correct.  We have issue #1208 for this.
