### ISSUE TITLE
fi_cntr_read() does not return with error when one has occured

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#1304]
I forgot to add FI_REMOTE_WRITE to hints->caps, but my fi_write() calls returned without error, and fi_cntr_read() only returned zero (and no error).  There were no warning messages either (this was a debug build).  When I called fi_cntr_readerr() the errors were counted there.

**Comment by sungeunchoi** [comment]
I'm wondering if this is that same as #1285

**Comment by jshimek** [comment]
Based on my reading of the current man page for fi_cntr_read and fi_cntr_readerr, it has no provision for telling you there is an error on the cntr_err... It looks like unless your using fi_cntr_wait you have to do both an fi_cntr_read and an fi_cntr_readerr, I would recommend opening a upstream ticket for clarification.

**Comment by sungeunchoi** [comment]
In the **RETURN VALUES** section is says:
```
Returns 0 on success. On error, a negative value corresponding to fabric errno is returned.
```
Seems like that should be enough to indicate error, tho I admit that it's not super specific.

**Comment by jswaro** [comment]
> fi_cntr_read  /  fi_cntr_readerr  :  Returns  the  current value of the counter.

I don't think you'd return negative values unless you couldn't read the counter. 

It's my interpretation of the man page that you would only really return a negative value for the following fi_cntr_* ops:
> fi_cntr_open, fi_close, fi_cntr_wait, and fi_cntr_control

The other functions are direct set, read or manipulation functions, where as the above are more administrative or function-oriented in nature. 

I believe this is something that should be clarified in the working group outside of the fi_read conversation, which is a very different type of operation. One is a counter operation, and the other is a data operation.

**Comment by sungeunchoi** [comment]
FYI @bcernohous pointed out that the fi_cntr_read and fi_cntr_readerr have unsigned return values and therefore cannot return any type of error.

**Comment by sungeunchoi** [comment]
Closing based on this and email discussions.  It seems that the recommended use of counters is to eventually call fi_cntr_readerr() if you don't have all your events in a timely manner.  This seems like it could be little tricky with remote counters if you don't know what remote events are coming your way.
