### ISSUE TITLE
Disable FI_MORE when FI_RMA_EVENT is set

### ISSUE THREAD

**Issue by a-abraham** [ofi-cray/libfabric-cray#1306]
When FI_RMA_EVENT is set, we send an event to the target to increment a remote counter. This is not currently supported by FI_MORE.

**Comment by hppritcha** [comment]
@a-abraham can this issue be closed now?

**Comment by a-abraham** [comment]
Yes - it looks like this PR disabled FI_MORE when FI_REMOTE_CQ_DATA and  FI_RMA_EVENT are set 
https://github.com/ofi-cray/libfabric-cray/pull/1207/files
