### ISSUE TITLE
fi_cntr_read hang on a wait object

### ISSUE THREAD

**Issue by bcernohous** [ofi-cray/libfabric-cray#1319]
![cntr](https://cloud.githubusercontent.com/assets/8314362/24727195/d03b18d2-1a1a-11e7-9f95-55eabc71b102.png)

A stack dump at the hang is attached.

I'm getting hangs on fi_cntr_read() when I set the wait object to FI_WAIT_UNSPEC.   

Using FI_WAIT_NONE circumvents the problem.

I thought FI_WAIT_UNSPEC would work since I do not use fi_cntr_wait in this code.

•  FI_WAIT_NONE : Used to indicate that the user will not block (wait) for events on the counter. 
•  FI_WAIT_UNSPEC : Specifies that the user will only wait on the counter using fabric interface calls, such as fi_cntr_wait. In this case, the underlying provider may select the most appropriate or highest performing wait object available, including custom wait mechanisms. Applications that select FI_WAIT_UNSPEC are not guaranteed to retrieve the underlying wait object.

**Comment by jshimek** [comment]
Pretty sure I know whats going on here, I'll push up a fix shortly.

**Comment by bcernohous** [comment]
A (dynamically linked) failing testcase is : /cray/css/users/bcernohous/osu-micro-benchmarks-5.3.2/openshmem/osu_ths_put_nbi.d.1319  

To run it, I'm still using a copying of Zach's fix library from last week:

$ export LD_LIBRARY_PATH=/cray/css/users/bcernohous/repos/mpt_base/components/xt-comp-gni/opt/cray/pe/pmi/5.0.11/lib64/:/cray/css/users/bcernohous/repos/mpt_base/smax/opt/lib/:/cray/css/users/bcernohous/repos/mpt_base/smax/libfab/install/lib/

It works by default (FI_WAIT_NONE)

$ OMP_NUM_THREADS=8 SHMEM_MAX_NUM_THREADS=8 SHMEM_MAX_NUM_CONTEXTS=8 SHMEM_THREAD_SAFETY=1 SHMEM_PROVIDER_DISPLAY=1 SHMEM_COLL_OPT_OFF=1 aprun -q -n2 -N1 -d12 /cray/css/users/bcernohous/osu-micro-benchmarks-5.3.2/openshmem/osu_ths_put_nbi.d.1319   heap
WARNING: libu: memcpy Intel cpuid detection failed
WARNING: libu: memcpy Intel cpuid detection failed
SELECTED PROVIDER:gni
Registering 8 threads
# OSU OpenSHMEM Non-blocking Put Test
# Size    PE                Latency (us)       Msg Rate (Hz)
1         0                         0.21          4723665.56
2         0                         0.17          5730659.03
4         0                         0.25          3926187.67
8         0                         0.17          5724098.45
16        0                         0.18          5694760.82
32        0                         0.18          5707762.56
64        0                         0.18          5691519.64
128       0                         0.32          3125976.87
256       0                         0.18          5630630.63
512       0                         0.18          5506607.93
1024      0                         0.20          5005005.01
2048      0                         0.39          2553626.15
4096      0                         0.51          1968503.94
8192      0                         1.18           848824.38
16384     0                         1.90           527472.53
32768     0                         3.58           279069.77
65536     0                         6.78           147465.44
131072    0                        13.36            74824.63
262144    0                        26.61            37573.39
524288    0                        53.23            18786.69
1048576   0                       111.26             8987.92

It hangs with FI_WAIT_UNSPEC on counters even though I use fi_cntr_read(), not fi_cntr_wait(). (SMAT_OFI_USE_WAIT_UNSPEC=1) 

$ SMAT_OFI_USE_WAIT_UNSPEC=1 OMP_NUM_THREADS=8 SHMEM_MAX_NUM_THREADS=8 SHMEM_MAX_NUM_CONTEXTS=8 SHMEM_THREAD_SAFETY=1 SHMEM_PROVIDER_DISPLAY=1 SHMEM_COLL_OPT_OFF=1 aprun -q -n2 -N1 -d12 /cray/css/users/bcernohous/osu-micro-benchmarks-5.3.2/openshmem/osu_ths_put_nbi.d.1319   heap
WARNING: libu: memcpy Intel cpuid detection failed
WARNING: libu: memcpy Intel cpuid detection failed
SELECTED PROVIDER:gni
Registering 8 threads
# OSU OpenSHMEM Non-blocking Put Test
# Size    PE                Latency (us)       Msg Rate (Hz)
1         0                         0.27          3677822.73
2         0                         0.26          3808073.12
4         0                         0.26          3874467.26
8         0                         0.26          3888024.88
16        0                         0.26          3829950.21
32        0                         0.26          3872966.69
64        0                         0.27          3743916.14
128       0                         0.26          3776435.05
256       0                         0.26          3792188.09
^C_pmiu_daemon(SIGCHLD): [NID 00235] [c1-0c0s10n3] [Wed Apr 12 13:49:08 2017] PE RANK 1 exit signal Interrupt
_pmiu_daemon(SIGCHLD): [NID 00234] [c1-0c0s10n2] [Wed Apr 12 13:49:09 2017] PE RANK 0 exit signal Interrupt

Pre-pending the latest CLE-6.X libfabric build shows no change.

$ LD_LIBRARY_PATH=/cray/css/users/libfabric-test/builds/latest-libfabric-CLE-6.X-debug/lib/:$LD_LIBRARY_PATH ldd ./osu_ths_put_nbi.d.1319 | grep fabric

        libfabric.so.1 => /cray/css/users/libfabric-test/builds/latest-libfabric-CLE-6.X-debug/lib/libfabric.so.1 (0x00007f1cfbfa1000)


$ LD_LIBRARY_PATH=/cray/css/users/libfabric-test/builds/latest-libfabric-CLE-6.X-debug/lib/:$LD_LIBRARY_PATH OMP_NUM_THREADS=8 SHMEM_MAX_NUM_THREADS=8 SHMEM_MAX_NUM_CONTEXTS=8 SHMEM_THREAD_SAFETY=1 SHMEM_PROVIDER_DISPLAY=1 SHMEM_COLL_OPT_OFF=1 aprun -q -n2 -N1 -d12 /cray/css/users/bcernohous/osu-micro-benchmarks-5.3.2/openshmem/osu_ths_put_nbi.d.1319   heap
WARNING: libu: memcpy Intel cpuid detection failed
WARNING: libu: memcpy Intel cpuid detection failed
SELECTED PROVIDER:gni
Registering 8 threads
# OSU OpenSHMEM Non-blocking Put Test
# Size    PE                Latency (us)       Msg Rate (Hz)
1         0                         0.22          4593477.26
2         0                         0.20          5096839.96
4         0                         0.19          5141388.17
8         0                         0.19          5151983.51
16        0                         0.20          5096839.96
32        0                         0.20          5120327.70
64        0                         0.20          5060728.74
128       0                         0.20          5017561.47
256       0                         0.20          5045408.68
512       0                         0.20          4955401.39
1024      0                         0.21          4672897.20
2048      0                         0.30          3292723.08
4096      0                         0.51          1952362.36
8192      0                         1.19           843099.23
16384     0                         1.82           548571.43
32768     0                         3.48           287425.15
65536     0                         6.89           145234.49
131072    0                        13.40            74650.08
262144    0                        26.77            37354.09
524288    0                        53.43            18717.10
1048576   0                       111.32             8982.88

$ LD_LIBRARY_PATH=/cray/css/users/libfabric-test/builds/latest-libfabric-CLE-6.X-debug/lib/:$LD_LIBRARY_PATH SMAT_OFI_USE_WAIT_UNSPEC=1 OMP_NUM_THREADS=8 SHMEM_MAX_NUM_THREADS=8 SHMEM_MAX_NUM_CONTEXTS=8 SHMEM_THREAD_SAFETY=1 SHMEM_PROVIDER_DISPLAY=1 SHMEM_COLL_OPT_OFF=1 aprun -q -n2 -N1 -d12 /cray/css/users/bcernohous/osu-micro-benchmarks-5.3.2/openshmem/osu_ths_put_nbi.d.1319   heap
WARNING: libu: memcpy Intel cpuid detection failed
WARNING: libu: memcpy Intel cpuid detection failed
SELECTED PROVIDER:gni
Registering 8 threads
# OSU OpenSHMEM Non-blocking Put Test
# Size    PE                Latency (us)       Msg Rate (Hz)
1         0                         2.97           336371.89
2         0                         0.29          3495281.37
4         0                         0.29          3479471.12
8         0                         0.29          3496503.50
16        0                         0.29          3497726.48
32        0                         0.28          3518648.84
64        0                         0.29          3472222.22
128       0                         0.29          3462603.88
256       0                         0.37          2696871.63
^C_pmiu_daemon(SIGCHLD): [NID 00235] [c1-0c0s10n3] [Wed Apr 12 13:48:32 2017] PE RANK 1 exit signal Interrupt
_pmiu_daemon(SIGCHLD): [NID 00234] [c1-0c0s10n2] [Wed Apr 12 13:48:32 2017] PE RANK 0 exit signal Interrupt
