### ISSUE TITLE
Intermittent amo hang on multi-threaded, multi-endpoint test

### ISSUE THREAD

**Issue by bcernohous** [ofi-cray/libfabric-cray#1322]
I get intermittent hangs with 4-16 endpoints on up to 16 threads, doing fetching amos.  I got stat-cl that shows lot of spin locks and not much else on rank 0. 
![hang](https://cloud.githubusercontent.com/assets/8314362/24821694/a8f1b190-1bb5-11e7-9c99-2b5a66591876.png)
 This is using the recent fix lib from Zach.

**Comment by hppritcha** [comment]
Have you picked up #1315 ?

**Comment by hppritcha** [comment]
@bcernohous can you retest with head of master to see if you're still observing this hang?

**Comment by bcernohous** [comment]
I ran 10 iterations with /cray/css/users/libfabric-test/builds/latest-libfabric-CLE-6.X-debug/lib/ and did not hang.

Hang (and new LIBSMA WARNING) :

$ OMP_NUM_THREADS=8 SHMEM_MAX_NUM_THREADS=8 SHMEM_MAX_NUM_CONTEXTS=8 SHMEM_THREAD_SAFETY=1 SHMEM_PROVIDER_DISPLAY=1 SHMEM_COLL_OPT_OFF=1 aprun -q -n2 -N1 -d12 ./osu_ths_atomics_nbi.d.1322   heap
WARNING: libu: memcpy Intel cpuid detection failed
WARNING: libu: memcpy Intel cpuid detection failed
SELECTED PROVIDER:gni
Registering 8 threads
 OSU OpenSHMEM Non-blocking Atomic Operation Rate Test
 Operation                        Million ops/s            Latency (us)

 PE 0 [Wed Apr 12 14:01:53 2017] [c1-0c0s10n2] [nid00234]  LIBSMA WARNING: An operation has not completed after an extended number of retries.

^C_pmiu_daemon(SIGCHLD): [NID 00234] [c1-0c0s10n2] [Wed Apr 12 14:01:57 2017] PE RANK 0 exit signal Interrupt
_pmiu_daemon(SIGCHLD): [NID 00235] [c1-0c0s10n3] [Wed Apr 12 14:01:57 2017] PE RANK 1 exit signal Interrupt

No Hang:

$ LD_LIBRARY_PATH=/cray/css/users/libfabric-test/builds/latest-libfabric-CLE-6.X-debug/lib/:$LD_LIBRARY_PATH OMP_NUM_THREADS=8 SHMEM_MAX_NUM_THREADS=8 SHMEM_MAX_NUM_CONTEXTS=8 SHMEM_THREAD_SAFETY=1 SHMEM_PROVIDER_DISPLAY=1 SHMEM_COLL_OPT_OFF=1 aprun -q -n2 -N1 -d12 ./osu_ths_atomics_nbi.d.1322   heap
WARNING: libu: memcpy Intel cpuid detection failed
WARNING: libu: memcpy Intel cpuid detection failed
SELECTED PROVIDER:gni
Registering 8 threads
 OSU OpenSHMEM Non-blocking Atomic Operation Rate Test
 Operation                        Million ops/s            Latency (us)
shmemx_int_fadd_nb                          0.39                    2.54
shmemx_int_finc_nb                          0.39                    2.55
shmemx_int_add_nb                           2.37                    0.42
shmemx_int_inc_nb                           2.39                    0.42
shmemx_int_cswap_nb                         0.39                    2.53
shmemx_int_swap_nb                          0.25                    4.04
shmemx_longlong_fadd_nb                     0.40                    2.53
shmemx_longlong_finc_nb                     0.39                    2.54
shmemx_longlong_add_nb                      2.37                    0.42
shmemx_longlong_inc_nb                      2.37                    0.42
shmemx_longlong_cswap_nb                    0.39                    2.54
shmemx_longlong_swap_nb                     0.21                    4.84

**Comment by hppritcha** [comment]
I think if I understand correctly this issue can be closed now?

**Comment by bcernohous** [comment]
yes
