### ISSUE TITLE
Should auxiliary data structures return libfabric specific error codes? 

### ISSUE THREAD

**Issue by bturrubiates** [ofi-cray/libfabric-cray#134]
I've been returning the FI_\* error codes, but I just noticed that the bitmap implementation returns EAGAIN instead of FI_EAGAIN. Should we standardize whether we use libfabric specific error codes within the auxiliary data structures? 

@hppritcha @ztiffany @sungeunchoi @jswaro

**Comment by hppritcha** [comment]
yes need to return FI error codes when practical.

---

sent from my smart phonr so no good type.

Howard

**Comment by jswaro** [comment]
I think that FI_\* error codes are fine.
