### ISSUE TITLE
mmap'ing to the same address and registering that memory results in stale data in fi_read

### ISSUE THREAD

**Issue by jpetro926** [ofi-cray/libfabric-cray#1350]
When I mmap and register that memory with fi_mr_reg(), then do an RMA read, everything works fine. If I close and munmap that memory, then re-mmap and re-register it, do an RMA read (after having written new data), the data from the previous iteration gets returned (even when I wipe out the local buffer).

I can work around this by increasing the address mmap'ed by a page in each iteration - then everything works fine. Additionally, (without the work around) the code will work with sockets.

So the procedure I'm using (in a loop) is:

    mmap()
    fi_mr_reg()
    <exchange keys, etc>
    fi_read()
    fi_close()
    munmap()

**Comment by jpetro926** [comment]
Setting GNI_RM_CACHE=none results in the above tests PASSing.

**Comment by biddisco** [comment]
This seems remarkably similar to a problem I was having recently where memory registered twice gave incorrect read results.
http://lists.openfabrics.org/pipermail/libfabric-users/2017-March/000248.html
Our fix was to disable the memory registration cache.

**Comment by jswaro** [comment]
@jpetro926 Can you attach a small testcase for me? I'll resolve this when I can.

**Comment by jpetro926** [comment]
I tested @jswaro's fix, and the failure is no longer occurring.
