### ISSUE TITLE
cq lock not acquired in gnix_cq_readerr

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#1359]
The CQ lock is released but never acquired in gnix_cq_readerr.

**Comment by jswaro** [comment]
Could you see if this is potentially related to #1312 ?

**Comment by chuckfossen** [comment]
The acquire was removed with @hppritcha commit e32205f8a3b688d17a08922c65e325d7fb27ee98
prov/gni: Fix problems with GNI cm nic progress

```
 -       __gnix_cq_progress(cq_priv);
 -       COND_ACQUIRE(cq_priv->requires_lock, &cq_priv->lock);
 +       _gnix_prog_progress(&cq_priv->pset);
```

**Comment by jshimek** [comment]
Do we need the cq lock here or do we just need to remove the COND_RELEASE?

**Comment by chuckfossen** [comment]
I think @hppritcha 's commit mentioned earlier is a mistake. I'm waiting for confirmation from him.
