### ISSUE TITLE
A Zeroed hints structure causes fi_getinfo to fail

### ISSUE THREAD

**Issue by jpetro926** [ofi-cray/libfabric-cray#1379]
Passing a hints structure allocated with `fi_allocinfo()` but otherwise unmodified to `fi_getinfo()` fails.  `FI_PROVIDER=gni` is set in the environment, otherwise sockets will be chosen.  Additionally, the call to `fi_getinfo()` seems to fail if an `mr_mode` is not specified in the hints despite any other values (though only `ep_attr->type`, `mode`, and `caps` were tried).  However, if `NULL` is passed instead of hints, the call will succeed.

Output: [test_fi_getinfo.txt](https://github.com/ofi-cray/libfabric-cray/files/1078974/test_fi_getinfo.txt)

**Comment by jswaro** [comment]
That is expected behavior. With a hint's structure, we need some definition of the application's capabilities. A zero'ed hints structure is not acceptable for the GNI provider until such time as more of the core features such as scalable memory registration are supported. 

Before I close, confirm that the following is being done by your test:
```C

hints = fi_allocinfo();
assert(hints);

memset(hints, 0x0, sizeof(*hints);

ret = fi_getinfo(fi_version(), NULL, NULL, 0, hints, &info)
assert(ret == FI_SUCCESS); // fails here
```

**Comment by jpetro926** [comment]
When I add the memset line, the second assert passes.  When I take it out, it fails.

**Comment by jswaro** [comment]
The memset isn't really necessary. I'm just guessing that was what your application was doing. Based on our conversation though, it seems like you are taking whatever is provided by fi_allocinfo and passing it directly through as the hints to the fi_getinfo call. Is that true?

**Comment by jpetro926** [comment]
Yes.

**Comment by jpetro926** [comment]
The behavior is clearer to me, now.  " *With the exception of mode bits*, hints that are set to zero are treated as a wildcard."  With a 0 mr_mode, I meant for it to be a wildcard, but it was specifying scalable memory registration.  Since GNI doesn't currently support this, it rightfully returned -FI_ENODATA.  This issue can be closed.
