### ISSUE TITLE
Should the bitmap return 0 or 1 as the starting index?

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#143]
While discussing another issue with a colleague, I realize that 0 at the starting index for the bitmap may be less than ideal. If we assume the value could be tied to a variable stored in another structure, 0 as a starting index would be bad because that could also be uninitialized memory. 

Is this a legitimate concern?

**Comment by hppritcha** [comment]
Looking at some other bitmap implementations, it looks like the x86 bsf is often used.  From my checks it returns a value using a zero-base offset.  Here's the test I used:

http://pastebin.com/THFd3wYp

I'd rather to with what's normally expected for bitmap behavior.  So if that means returning 0 if the LSB 0 in a 64 bit word is set, than let's go that way.

**Comment by jswaro** [comment]
Fine by me then, closing
