### ISSUE TITLE
Add basic memory registration (fi_mr_ops)

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#147]
mr_reg and mr_dereg needs to be implemented for basic send/recv operations

@hppritcha, @ztiffany , @sungeunchoi 

Please add more content, suggestions, etc ...

**Comment by jswaro** [comment]
All memory registrations should be tied to the device's tx cq right?

**Comment by jswaro** [comment]
So we have two flavors of rx CQs. Which one gets used and how do we determine that?

@hppritcha , @ztiffany

**Comment by hppritcha** [comment]
For just plan memory registration (not for use with GNI SMSG or the special case of maybe using the blocking rx cq with the provider internal dma buffers), I wouldn't expect we would register the user buffers for fi_read/write amo using a GNI CQ.
