### ISSUE TITLE
Add memory registration cache for FI_LOCAL_MR path

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#148]
In cases where the application doesn't handle the memory registrations, we should use a memory registration cache for holding memory registrations locally until they aren't needed. We could hold registrations under the premise that they could be reused again within a short period of time to avoid costly registration and deregistration calls. 

@sungeunchoi , @hppritcha , @ztiffany 

Please feel free to contribute ideas.

**Comment by jswaro** [comment]
It seems like FI_LOCAL_MR is advice to application rather than a mode on the domain. 

How do we determine if a registration needs to be in a cache rather than managed by the application?

**Comment by nenadv** [comment]
As we are working on the UPC runtime at the top of libfabric, I started the same conversation with other developers and this is what I got back on the subject:

```
The mode bits are 2-way communication between app and provider regarding
which provider restrictions the app is ready to deal with.

If the app is ready to deal with a restriction (say FI_LOCAL_MR that
requires buffers sent to be registered locally), but the provider doesn’t
require it, it can clear that mode bit.

The app can then inspect the mode bit outcome and relax its usage
depending on what the provider returned.

What the provider cannot do is to impose additional restrictions than what
the app was ready to deal with. E.g. If you clear out FI_LOCAL_MR in mode
bits on input, the provider cannot set this bit on outcome.

I think Cray provider will require local memory registration.
```

It seems that if you don't cache you need to return an error if FI_LOCAL_MR is not specified?
