### ISSUE TITLE
c11 atomics code should get pushed back upstream 

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#165]
The c11 atomics code in gnix_atomics.h should be pushed back upstream to ofiwg/libfabric.

**Comment by jswaro** [comment]
There is a copy/paste error in atomic_sub. I've fixed it as part of the registration cache work since I needed atomic_sub there.

**Comment by jswaro** [comment]
The copy/paste error is fixed. This could probably be done now if we wanted.
