### ISSUE TITLE
Create valgrind surpression file

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#176]

**Comment by jswaro** [comment]
Question is, where do we want to put this ?

I wrote a quick python script to generate the suppressions and automatically name them by the last two functions in the stack. This seems sufficient and it works. We should review this together to get an idea of what functions we want to suppress, such as the IOCTL problems.

**Comment by hppritcha** [comment]
in the ompi project there's a "contrib" directory at the top level where items like a valgrind suppression file go.  Perhaps we could do the same?

**Comment by sungeunchoi** [comment]
Top level of prov/gni?  They're gni specific, right?

Oh and :+1:  for contrib.  That seems common.
