### ISSUE TITLE
Design mapping of fence operation

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#220]

**Comment by hppritcha** [comment]
Decided that what we would do for now is that when a op with FI_FENCE flag is submitted, would check if pending send or outstanding rma/amo reqs in progress.  If yes, queue on the `send_queue`.  Increment a `fenced_op_cnt` field.  Subsequent rma/amo reqs would then continue to be queued on to the send queue until the request with the FI_FENCE is injected in to the fabric.

So we'll need an extra field in the `gnix_vc` to keep track of outstanding fenced ops.
