### ISSUE TITLE
Design mapping of atomics to Aries AMOs

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#222]
- Which atomics to support (possibly only _native_)?
- Which atomics are used by pgas?

**Comment by nenadv** [comment]
PGAS (at least UPC language) uses almost all atomics as specified in the libfabric API.  Here is the list:

```
Types:
#define UPC_CHAR        1
#define UPC_UCHAR       2
#define UPC_SHORT       3
#define UPC_USHORT      4
#define UPC_INT         5
#define UPC_UINT        6
#define UPC_LONG        7
#define UPC_ULONG       8
#define UPC_LLONG       9
#define UPC_ULLONG      10
#define UPC_INT8        11
#define UPC_UINT8       12
#define UPC_INT16       13
#define UPC_UINT16      14
#define UPC_INT32       15
#define UPC_UINT32      16
#define UPC_INT64       17
#define UPC_UINT64      18
#define UPC_FLOAT       19
#define UPC_DOUBLE      20
#define UPC_LDOUBLE     21
#define UPC_PTS         22

Operations:
#define UPC_ADD_OP         0
#define UPC_MULT_OP        1
#define UPC_AND_OP         2
#define UPC_OR_OP          3
#define UPC_XOR_OP         4
#define UPC_LOGAND_OP      5
#define UPC_LOGOR_OP       6
#define UPC_MIN_OP         7
#define UPC_MAX_OP         8
#define  UPC_GET_OP    9
#define  UPC_SET_OP    10
#define  UPC_CSWAP_OP  11
#define  UPC_SUB_OP    12
#define  UPC_INC_OP    13
#define  UPC_DEC_OP    14
```

In our implementation, UPC_PTS (shared pointer) can be 64 bits (packed implementation) and 128 bits (struct implementation).  Same with Berkeley UPC.  I think that Chapel is 128 bits.

Note that for a long time (both in portals and libfabric) we argued for 128 bits unsigned integer swap/cswap operations that we can use for shared pointers.

**Comment by sungeunchoi** [comment]
I'm assuming that if a particular size or operation is not supported by hardware or the API, there is a library implementation?

FWIW, Chapel's notion of the shared pointer wide is 128 bits (there is a packed implementation that is not well supported since it does not easily support hierarchical locales).  These are not exposed to the user, but a something like a 128 bit swap operation could be useful for the implementation of certain Chapel level constructs.

@gbtitus

**Comment by nenadv** [comment]
On 6/9/15 2:10 PM, Sung-Eun Choi wrote:

> I'm assuming that if a particular size or operation is not supported by
> hardware or the API, there is a library implementation?

Yes. At the moment we have UPC atomics implementation that uses atomics
provided by the socket provider. They support everything that is in
libfabric API, and I think you need to provide the same as I haven;t
seen an interface that would allow you to drop certain types of atomic
operations.

**Comment by sungeunchoi** [comment]
The atomic valid functions indicate which operations are supported by a provider, and I don't see anything in the fi_atomic man page that says that any of them are strictly required.  Obviously, operations supported directly by the hardware should be included, but it's not clear about the others.  That said, if the GNI provider can implement the operation more easily/efficiently than a client can, it seems like it should be supported.

I know that Sean is working on a design for a framework to support operations that a specific provider may not implement, in an effort to aid portability.  I don't seen an open issue for that, but it was discussed at one of the recent meetings, and I could imagine that all the atomics would fall under that umbrella.

**Comment by nenadv** [comment]
Ah yes, its been a while. This approach does not work well for us as we
have to configure the runtime per provider, or check in init time and
possible install different handlers.  This will force us to keep two
implementations around at all time.

**Comment by sungeunchoi** [comment]
I agree that this sounds onerous.  Would it be helpful to be able to know early on, say from fi_getinfo, what operations are supported?  In the very least it seems like it would be nice to have a single call to tell you what is valid.  Might be worth raising an issue on ofiwg/libfabric.

**Comment by hppritcha** [comment]
Discussed usage of PCI-e gen3 atomics with Aries HW designers.  Problem here is that support for such ops only came in with Ivy Bridge processors.  128b CAS is not supported currently.

The Aries HW can support all of the UPC datatypes listed above, although some will map more efficiently to the hardware than others, depending on the type of operation, assuming UPC_LDOUBLE can be mapped to UPC_DOUBLE.
