### ISSUE TITLE
Disabling checks from the linux style checker

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#224]
@jswaro @ztiffany @jshimek @hppritcha 

Using this script as a pre-commit doesn't allow us to make exceptions, so disabling some checks is a decent way to get around it.

**Comment by ztiffany** [comment]
This wasn't useful to me:

WARNING: unnecessary whitespace before a quoted newline
#3439: FILE: ported/osu/rdm_mbw_mr.c:69:

**Comment by ztiffany** [comment]
I hate this:

WARNING: braces {} are not necessary for single statement blocks
#544: FILE: ported/osu/rdm_mbw_mr.c:532:

**Comment by ztiffany** [comment]
I could take or leave this:

ERROR: do not initialise statics to 0 or NULL
#51: FILE: ported/osu/ft_utils.c:214:

**Comment by ztiffany** [comment]
This should be a judgement call:

WARNING: quoted string split across lines
#336: FILE: ported/osu/rdm_mbw_mr.c:109:

**Comment by sungeunchoi** [comment]
Disabled all but "ERROR: do not initialise statics to 0 or NULL"
