### ISSUE TITLE
Initial support for OpenMPI

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#236]
See #211
- [x] tag matching #240 
- [x] fi_send/fi_recv for arbitrary length messages #243
- [x] Variants of fi_send/fi_recv #244

Bonus: fi_cancel #245

Testing:
- FI_RDM, FI_MSG fabtests
- fabtests port of OSU benchmarks
- IMB

**Comment by jswaro** [comment]
I think this is done right?
