### ISSUE TITLE
Implement tag matching

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#240]
See #227

**Comment by jswaro** [comment]
@hppritcha 

So I'm getting some time to work on this. I think I have my head around the ignore bit system and I am factoring that into the design. I need to know more information though, if we are going to make this optimal. We can also do a simple design to start.

So facts that I know at the moment first:
1. The ignore bits can be a multi-section mask. IE, 0x30F is a valid mask with 3 distinct sections.
2. Unique tags must be used in the order in which they were delivered. (sequencing)
3. Users cannot provide an ignore mask that spans two different sections of a mask.

So here are a few of my questions to start drafting a design.
1. Can tags be non-unique? 
2. If multiple tags could match a particular ignore mask, particularly in the wildcard case, should the oldest tag be returned, or just the oldest tag in a specific bin?

I'll add more to these lists later

**Comment by jswaro** [comment]
I should provide some visuals to my questions.

Regarding tag format:
1. Where is the tag format stored? I browsed the basic data structures and did not find it. The man pages don't hint at one. 
2. IIRC, the tag format can be something like 0x107. If memory serves, this would be a 3 distinct section tag. What determines the length of the section with the zero? Is it not possible that someone might do a odd number of bits within that section?

**Comment by hppritcha** [comment]
2015-07-16 9:10 GMT-06:00 James Swaro notifications@github.com:

> @hppritcha https://github.com/hppritcha
> 
> So I'm getting some time to work on this. I think I have my head around
> the ignore bit system and I am factoring that into the design. I need to
> know more information though, if we are going to make this optimal. We can
> also do a simple design to start.
> 
> So facts that I know at the moment first:
> 1. The ignore bits can be a multi-section mask. IE, 0x30F is a valid mask
> with 3 distinct sections.
> 2. Unique tags must be used in the order in which they were delivered.
> (sequencing)
> 3. Users cannot provide an ignore mask that spans two different sections
> of a mask.
> 
> So here are a few of my questions to start drafting a design.
> 1. Can tags be non-unique?
> 
> yes, sends with the same tag have to be matched in order by posted receives
> that match the tag under the ignore bits mask.
> 1. If multiple tags could match a particular ignore mask, particularly in
>    the wildcard case, should the oldest tag be returned, or just the oldest
>    tag in a specific bin?
> 
> that's where things get complicated.  For the unexpected receive side,  MPI
> doesn't define an order for match.  But for posted receives, the matching
> sender
> must match the oldest posted receive that can match the incoming messages
> tag under the ignore bits mask.  I bet this isn't clear in the libfabric
> man pages though.

I'll add more to these lists later

**Comment by jswaro** [comment]
So there are going to be three passes at getting the tag matching correct. 

The first pass will be a simple doubly-linked list to ensure proper function.

The second pass will be a hash list of doubly linked list on a field in the tag format provided by the user. If there is no tag format, this doesn't provide us any benefit and we can fallback to a simple doubly-linked list. 

The third pass MAY be a spatially-aware KD tree implementation with bound limitations based on sequencing. This is a optimization for searching in k log D time. Even if applications fore go the use of the ignore bits, we can use the sequence bounded searching to prevent N length linear searches.
