### ISSUE TITLE
Allow client to tune parameters for fi_send/fi_recv and friends

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#242]
e.g., SMSG cut-off size, when to switch to rendezvous, etc.

**Comment by sungeunchoi** [comment]
@hppritcha Do you think these fi_msg parameters should be defined per endpoint?

**Comment by hppritcha** [comment]
It would be ideal to adjust SMSG size on a per endpoint basis but it would have some difficulties.  We can discuss at next telecon if you'd like.

**Comment by hppritcha** [comment]
I put a topic branch up on my repo that has a `fi_ops_open`  string in comments around the many places where we might want to use fi_open_ops to set parameters for objects instantiated from a given domain object.

https://github.com/hppritcha/libfabric/tree/topic/fi_open_ops_todos
