### ISSUE TITLE
Support for GUPC/Clang-UPC

### ISSUE THREAD

**Issue by nenadv** [ofi-cray/libfabric-cray#270]
The following libfabric functionality is used by the GNU UPC and Clang UPC runtime:
## Endpoint
- Scalable endpoints (minimizes endpoints data to exchange)
- Shared endpoints on TX side (recommended by developers by NOT implemented)
- Endpoints created with FI_DELIVERY_COMPLETE option
- Counter/CQ associated with each endpoint on TX side
## Memory Region
- fi_mr_reg
- fi_mr_bind

Counter for incoming writes associated with MR on some endpoints.

NOTE: Currently, there is no memory region associated with local memory, but I suspect that will not be the case with Cray
## Remote Memory Access
- fi_write
- fi_inject_write
- fi_read
## Completion counter

*\* all calls except add/set
## Completion queues
- fi_cq_read
- fi_cq_readerr
- fi_cq_strerror
## Address Vector Operations
- open/insert
- FI_AV_TABLE for endpoints
## Atomic Functions
- fi_atomic
- fi_fetch_atomic
- fi_compare_atomic

All data types except COMPLEX.

Operations:
- FI_SUM, FI_PROD, FI_MAX, FI_MIN, FI_BAND, FI_BOR, FI_BXOR
- FI_ATOMIC_READ, FI_ATOMIC_WRITE, FI_CSWAP

**Comment by hppritcha** [comment]
Thanks Nenad.  The counters on the memory regions might be a little tricky to do in a high performance way.

**Comment by sungeunchoi** [comment]
At last communication, all GNU UPC tests pass with GNI provider.
