### ISSUE TITLE
Prevent network operations on endpoints without a send CQ

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#272]

**Comment by hppritcha** [comment]
@ztiffany 
perhaps we should check for send_cq being non-NULL on the ep when `fi_enable` is invoked?

**Comment by hppritcha** [comment]
From the libfabric fi_endpoint man page:

```
Active endpoints are created in the disabled state.  They must
transition into an enabled state before accepting data transfer
operations, including posting of receive buffers.  The fi_enable call
is used to transition an endpoint into an active enabled state.  The
fi_connect and fi_accept calls will also transition an endpoint into
the enabled state, if it is not already active.
```

need to ping mail list about whether an endpoint has to be bound to a CQ if it never solicits CQ events.

**Comment by sungeunchoi** [comment]
Also from the fi_endpoint man page:

```
An endpoint must be bound with CQs capable of reporting completions for any asynchronous operation
initiated on the endpoint. This is true even for endpoints which are configured to suppress successful
completions, in order that operations that complete in error may be reported to the user.
```

I think this means 'yes.'

**Comment by ztiffany** [comment]
A few fabtests do some operations without a send CQ, so I think this is a valid use.  I have a PR out to allow operations to be done without CQs bound to the EP.

**Comment by ztiffany** [comment]
I think we should include this in the work for #345.  Asynchronous operation should return an error if a CQ is not bound to receive the associated events.  Thoughts? @hppritcha @chuckfossen @sungeunchoi

**Comment by sungeunchoi** [comment]
I'm still not sure what the answer is here.  Are we trusting the fabtests or the man page?

**Comment by ztiffany** [comment]
To me, the man page doesn't say anything about enabling without a send CQ.  The problem is initiating an asynchronous operation without a send CQ.

```
An endpoint must be bound with CQs capable of reporting completions for any asynchronous operation
initiated on the endpoint.
```

**Comment by sungeunchoi** [comment]
Ah -- I see what you're saying.

**Comment by sungeunchoi** [comment]
For the sending side, need to check that an appropriate CQ for the operation type is bound to the endpoint.
- Send CQ is require for all basic send types except inject
- A receive CQ is required for posting a receive operation
- Return -FI_ENOCQ if no CQ bound (as per most recent fi_endpoint man page) #704
