### ISSUE TITLE
Use of fi_allocinfo_internal() causes link-time failures

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#28]
`fi_allocinfo_internal` is a static function and given the name doesn't seem like it's part of a public interface.  This causes build time warnings when compiling libfabric and link-time failures when building any tests.

It's not a fancy function, so it seems reasonable to replicate, tho it would be nice to have this be an externally exposed function.

@hppritcha

**Comment by hppritcha** [comment]
sorry just saw this, yes switching to the now public fi_allocinfo is the right thing here.
