### ISSUE TITLE
rdm_rma unit tests fail with assertion in gnix_ep_control()

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#292]
gnix_ep_control: Assertion `ep->recv_cq != ((void *)0)' failed.

**Comment by sungeunchoi** [comment]
@hppritcha @ztiffany 

The issue here is that in Zach's rdm_rma tests, a single cq is bound to a single endpoint for FI_SEND only, as that is all that is needed.  The assertion is hit since there is no recv cq bound to the endpoint.  Also the 2nd endpoint does not have any cq's bound to it.  If I change the test to bind a cq to both endpoints for FI_SEND | FI_RECV (as in the rdm_msg test), this test passes (minus the assertion fixed in #295).  Similarly, if I remove the assertion, these tests pass (as expected, since they pass when assertions are compiled out).

I don't see any requirement for cq being bound to endpoints, so should we remove this assertion or was there some other reason for it?

**Comment by hppritcha** [comment]
I'm pretty convinced that the assert on `recv_cq` shouldn't be there.  The `fi_enable` call doesn't appear to require that an app have bound a CQ to an EP for receive events when enabling the ep.
