### ISSUE TITLE
Rename/rework free functions for structures that are reference counted

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#296]
Motivated by comments on #295 by @jswaro regarding _gnix_nic_free

The name _free_ implies freeing memory, but sometimes it just decrements the reference count, so maybe rename such functions to be more clear.  I'd also suggest wrapping the ref count increment function to make it symmetric.

**Comment by jswaro** [comment]
I'd propose the following:

*_get - increases ref count
*_put - decrease ref count and calls destructor for object at 0 references
*_destruct - destruct related code for object

I did something similar for the memory registration entries, __mr_cache_entry_get/put/destroy. Those functions are little more complex than we are suggesting here, but it maintains the property of keeping the deallocation/destruct code separate from the reference handling.

**Comment by jswaro** [comment]
hold/put is also commonly used in the kernel to my knowledge.

**Comment by hppritcha** [comment]
the get/put/destruct approach sounds good to me.
