### ISSUE TITLE
Check for memory leaks with valgrind

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#338]
See suppression file in prov/gni/contrib

**Comment by hppritcha** [comment]
I think we should run a sanity valgrind test at least on fabtests.

**Comment by sungeunchoi** [comment]
I ran valgrind on gnitest, and found the following:
- 4 bytes lost from strdup() in gnix_getinfo
- 2,048 bytes lost from calloc() in __gnix_ht_lf_init_new_table
- 9,216 bytes lost from calloc() in __gnix_ht_lk_init_new_table

**Comment by sungeunchoi** [comment]
The 4 bytes are due to an upstream issue posted to ofiwg/libfabric (https://github.com/ofiwg/libfabric/issues/1371).

**Comment by sungeunchoi** [comment]
Fixed the first leak with #408
