### ISSUE TITLE
Test the rest of the wait interfaces

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#342]
- Review what's already being tested
- Could this be covered by getting fabtets working?

**Comment by sungeunchoi** [comment]
Only fabtests is fi_dgram_waitset.

**Comment by jshimek** [comment]
Wait objects are used for any tests using fi_cq_sread/from, fi_eq_sread/from, fi_cntr_wait.

**Comment by jshimek** [comment]
Tests were added to the gni provider to verify and validate the wait systems infrastructure as part of PR #1034.
