### ISSUE TITLE
Restrict API to interfaces requested in domain hints

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#345]

**Comment by hppritcha** [comment]
To clarify, we should not allow, for example, atomic ops on endpoints from a domain  where the user did not request the atomic op capability.

**Comment by chuckfossen** [comment]
@hppritcha, what return code should I use? FI_EACCES?

**Comment by chuckfossen** [comment]
I'm looking at the capabilities section of fi_info in the manual.
The paragraph:

"FI_RMA  : Specifies that the endpoint should support RMA read and write operations.  Endpoints supporting this capability support operations defined by struct fi_ops_rma.  In the absence of any relevant flags, FI_RMA implies the ability to initiate and be the target of remote memory reads and writes.  Applications can use the FI_READ, FI_WRITE, FI_REMOTE_READ, and FI_REMOTE_WRITE flags to restrict the types of RMA operations supported by an endpoint."

seems to imply that (for instance) if the FI_READ flag is set, the rest of the operations are not permitted. Or, does it mean that setting the flag restricts that operation?

**Comment by sungeunchoi** [comment]
I believe if you set a flag (e.g., FI_READ), then only those operations are permitted.  At least that's how we've written our tests.

**Comment by hppritcha** [comment]
I agree with Sung's assessment.

**Comment by hppritcha** [comment]
@chuckfossen I think `-FI_EOPNOTSUPP` might be more appropriate.

**Comment by ztiffany** [comment]
See src/enosys.c.  You could set EP ops pointers during EP creation to prevent a given type of operation.  See an example of this in gnix_cq.c where cq->ops->sread pointer is set to fi_no_cq_sread if a valid wait object is not used.  All these fi_no_\* functions just return -FI_ENOSYS.

For FI_REMOTE_READ and FI_REMOTE_WRITE we could store the caps from a connected peer with VC data to be checked before an operation is tried.
