### ISSUE TITLE
properly support FI_SOURCE if GNI provider advertises this capability

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#348]
We currently advertise `FI_SOURCE` capability for GNI provider but its not fully implemented.
Internally the provider does have all the info - via the `gnix_vc` struct, to provide this info, but currently the gnix_fid_cq methods in gnix_cq.c don't allow setting the `source` field in the cq entry.

**Comment by hppritcha** [comment]
This needs to be addressed with or before issue #349

**Comment by ztiffany** [comment]
I started looking at #349 before seeing this.  Are you still working on this, Howard?

**Comment by hppritcha** [comment]
@ztiffany not at the moment.  please charge ahead.
