### ISSUE TITLE
fi_av_insert inserts user memory

### ISSUE THREAD

**Issue by bcernohous** [ofi-cray/libfabric-cray#384]
When using av_type: FI_AV_TABLE and :

 num_inserted=(av,
                            names,
                            size,  NULL, 0, NULL);

  free(names);

I suspect you are pointing your table enries into my names storage, which I free shortly after the fi_av_insert.  

So my storage gets reused and reinitialized at some random time later and av operations fail.

**Comment by hppritcha** [comment]
turns out I need to do some work in av table anyway.  reassigning to myself.
