### ISSUE TITLE
valgrind: Invalid read in cntr_setup

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#396]
In all cntr tests:

==8762== Invalid read of size 8
==8762==    at 0x40AE07: cntr_setup (fi_endpoint.h:167)
==8762==    by 0x43CAD6: run_test_child (runner.c:138)
==8762==    by 0x43D229: run_worker (process.c:67)
==8762==    by 0x43D34B: spawn_test_worker (process.c:93)
==8762==    by 0x43CE3A: criterion_run_all_tests (runner.c:190)
==8762==    by 0x403D03: main (main.c:184)
==8762==  Address 0x10 is not stack'd, malloc'd or (recently) free'd

**Comment by hppritcha** [comment]
my test I'll take this.
