### ISSUE TITLE
Set SMSG max retransmits count using GNI_MAX_RETRANSMITS

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#452]
The GNI_MAX_RETRANSMITS provider ops value should be used to set the SMSG max retransmit count for each endpoint.  See GNI_SmsgSetMaxRetrans().

**Comment by sungeunchoi** [comment]
Do we want this to use this same retransmit limit or does it make sense to use a different variable?

@ztiffany @hppritcha

**Comment by ztiffany** [comment]
I think the same limit works.  This won't need to be finely tuned.
