### ISSUE TITLE
Implement FI_MORE

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#454]

**Comment by sungeunchoi** [comment]
See https://github.com/ofiwg/libfabric/issues/1218 for discussions on an alternative proposal to FI_MORE.

**Comment by sungeunchoi** [comment]
Needed for:
- fi_msg
- fi_tagged
- fi_rma
- fi_atomic

**Comment by a-abraham** [comment]
implementation of fi_more for fi_rma is complete, pending man page updates etc.

**Comment by ztiffany** [comment]
Considering FI_MORE is primarily for one sided and we don't have any great prospects for optimizing send/recv or atomics, I think we might be done with this one.

**Comment by sungeunchoi** [comment]
Minus the outstanding bugs, I agree.
