### ISSUE TITLE
Implement FI_THREAD_COMPLETION

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#457]

**Comment by jswaro** [comment]
Directly related to #461

**Comment by hppritcha** [comment]
outcome of discussion at WAR #4.

FI_THREAD_COMPLETION looks promising for removing fast lock and rwlock calls within the nic progress loop.  If this level of thread safety is requested, it implicitly specifies FI_PROGRESS_MANUAL for the domain.  This feature will also require a more refined approach to selecting the `gnix_nic` to be associated with an `gnix_fid_ep`.   In addition to checking for matching cookie, the thread safety level of the `gnix_nic` will also need to be checked.

**Comment by jswaro** [comment]
closed by #776
