### ISSUE TITLE
FI_MR_SCALABLE scope out supporting this in GNI provider

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#458]
The GNI/Aries software stack has some limitations that makes implementing `FI_MR_SCALABLE` difficult, but perhaps not impossible,  to do in a performant manner.  This issue tracks various areas that need to be investigated:
- [ ] VMDH hardware - how can this be used?
- [ ] MSR feature - can this be used?  How do we handle ODP?
- [ ] could we use CQE  AT error codes to handle ODP?
- [ ] alternatives besides GASNET fire-hose like algorithms

Could we implement something between `Fi_MR_BASIC` and `FI_MR_SCALABLE`  that would work well for PGAS models?

**Comment by sdvormwa** [comment]
> Could we implement something between FI_MR_BASIC and FI_MR_SCALABLE that would work well for PGAS models?

I'm starting to take a stab at this in my [vmdh branch](https://github.com/sdvormwa/libfabric-cray/tree/vmdh) by exposing both VMDH and the GNI_MEM_RESERVE|GNI_MEM_UPDATE flags to the client as transparently to the fabric as possible, basically pushing all management of these registrations off to the client.  I think this level of functionality is sufficient to work well for PGAS models while not being too onerous on the fabric.  For the moment, I'm planning on implementing these as extensions via domain ops.

**Comment by hppritcha** [comment]
closing this since we have a bunch of other PRs/issues tracking support for mr scalable.
