### ISSUE TITLE
Review and update use of GNIX_ERR

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#467]
#449 will change GNIX_ERR to abort, so review current uses of it and replace with GNIX_WARN, where the error should not be fatal (e.g., if an error is returned to the user and it is recoverable).

**Comment by sungeunchoi** [comment]
- Consider adding GNIX_ABORT or GNIX_FATAL
- GNIX_ERR: possibly recoverable by client
- GNIX_WARN: something could be wrong

**Comment by chuckfossen** [comment]
How I am approaching this is:
- Add a GNIX_FATAL: prints message unconditionally and aborts
- GNIX_ERR: prints message unconditionally
- GNIX_WARN: no change
  Change GNIX_ERR calls to GNIX_WARN where the error is being handled appropriately.

Let me know if this is not satisfactory.

**Comment by jswaro** [comment]
I'm fine with that approach.
