### ISSUE TITLE
fi_recv() causes deadlock with lazy deregistration disabled and auto-registration.

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#469]
When using fi_recv() without specifying an mdesc and with lazy deregistration disabled, deadlock can occur when the target buffer is deregistered inside the SMSG FIN callback (nic->lock is held).

**Comment by ztiffany** [comment]
Now that I think about it, we might be able to solve this by removing locks around GNI_MemRegister/MemDeregister.  In past investigations, I've found that the GNI memory registration code is all thread safe.

**Comment by hppritcha** [comment]
@ztiffany could you double check that we can get away with not locking for mem registration even if VMDH is being used?  Otherwise this would help a lot if we could remove the lock around these mem reg/dereg calls.

**Comment by ztiffany** [comment]
Using VMDH would not be thread safe.  That looks like the only exception.
