### ISSUE TITLE
Add hash table implementation.

### ISSUE THREAD

**Issue by bturrubiates** [ofi-cray/libfabric-cray#47]
We are in need of a hash table implementation for use in several places. One area in specific that a hash table would be needed is the FI_AV_MAP implementation. Currently I am not storing the stored addresses, and am just fabricating the return value.

**Comment by hppritcha** [comment]
We will also need an efficient hash table to handle the virtual connection structure that the gni provider will use internally for managing smsg connections.

**Comment by hppritcha** [comment]
This should go in a separate file + header file.

**Comment by hppritcha** [comment]
We are okay with a simple fixed uint64_t key.  The value can just be pointer.  Insertion/deletion will be infrequent, but lookup will be very frequent.

**Comment by jswaro** [comment]
I'm having some difficulty in finding an open source hash table implementation that is either properly licensed, functional or fast. What requirements do we have for the hash table implementation (besides what is mentioned above)?

I'm making the following assumptions:
-- insertion/deletion must be thread safe
-- retrieval of a value from the map must not be prone to races
-- lookups must be fast

Are we ultimately looking for something simple, or expandable, robust, and fully featured? 

@hppritcha @sungeunchoi @ztiffany @bturrubiates

**Comment by hppritcha** [comment]
Sorry did not see this update earlier.  Your assumptions below are right.
I think we can go for simple right niw then revisit later with a more
comprehensive solution if we are seeing bad perf problems.
