### ISSUE TITLE
Speed up criterion tests

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#471]
I'd prefer keeping criterion tests very short (small fractions of a second each).  The following tests take very long:

[RUN ] endpoint::open_close
[PASS] endpoint::open_close: (13.31s)

[RUN ] gnix_tags_basic_posted_list::multiple_8192_ipr_random_tag
[PASS] gnix_tags_basic_posted_list::multiple_8192_ipr_random_tag: (11.34s)
[RUN ] gnix_tags_basic_posted_list::multiple_8192_ipr_sequential_tag
[PASS] gnix_tags_basic_posted_list::multiple_8192_ipr_sequential_tag: (10.05s)

[RUN ] gnix_tags_basic_unexpected_list::multiple_8192_ipr_random_tag
[PASS] gnix_tags_basic_unexpected_list::multiple_8192_ipr_random_tag: (11.37s)
[RUN ] gnix_tags_basic_unexpected_list::multiple_8192_ipr_sequential_tag
[PASS] gnix_tags_basic_unexpected_list::multiple_8192_ipr_sequential_tag: (9.98s)

**Comment by sungeunchoi** [comment]
endpoint::open_close is designed to be a stressor (as is domains::many_domains).  Should we move such stressors into a separate criterion test?
