### ISSUE TITLE
Fix assertion in __nic_vc_progress

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#473]
When asserts are enabled, rdm_rx_overrun::all_to_one fails during __nic_vc_progress.  Specifically it hits the assertion in _gnix_vc_push_tx_reqs() in gnix_vc.:1355.

**Comment by ztiffany** [comment]
I'm seeing a different error in rdm_rx_overrun::all_to_one: 

libfabric:gni:ep_ctrl:_gnix_vc_schedule():1186<info> [14865:2] Scheduled VC (0x943b50)
libfabric:gni:ep_ctrl:_gnix_nic_next_pending_vc():1216<info> [14865:2] Dequeued VC (0x943b50)
libfabric:gni:ep_ctrl:__gnix_vc_post_test_clbk():159<trace> [14865:2] 
libfabric:gni:ep_ctrl:__gnix_vc_process_datagram():587<trace> [14865:2] 
libfabric:gni:ep_ctrl:__gnix_vc_post_test_clbk():159<trace> [14865:10] 
libfabric:gni:ep_ctrl:__gnix_vc_process_datagram():587<trace> [14865:10] 
libfabric:gni:ep_ctrl:__gnix_vc_hndl_con_match_con():216<trace> [14865:10] 
gnitest: prov/gni/src/gnix_vc.c:645: __gnix_vc_process_datagram: Assertion `0' failed.
[----] prov/gni/test/rdm_rx_overrun.c:216: Unexpected signal caught below this line!

This is probably not worth fixing until after Howard's changes to connection management.

**Comment by sungeunchoi** [comment]
I ran into this before your retransmit commits this week, so maybe the error has moved?

**Comment by sungeunchoi** [comment]
I fixed a couple issues with the test program, but it still fails in the same way.  If I reduce NUM_EPs to 5, the test usually passes, but sometimes hangs while waiting for the first receive to complete.

**Comment by sungeunchoi** [comment]
With recent changes, we no longer hit this assertion with this test case.

@nenadv Do you know if you are still seeing it?
