### ISSUE TITLE
GNI_CqDestroy returned GNI_RC_INVALID_PARAM with FI_LOG_LEVEL warn

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#484]
Several of the fabtests (e.g. fi_rdm_tagged_pingong), as well as all of the osu MPI tests that work, will emit an warning about `GNI_CqDestroy` returning `GNI_RC_INVALID_PARAM` if the FI_LOG_LEVEL env. variable is set to warn.

This should be cleaned up prior to merging upstream

**Comment by sungeunchoi** [comment]
The rest of these are due to not cleaning up the VC in the endpoint vc_ht.  Working on a fix now.
