### ISSUE TITLE
GNI provider needs to handle FMA unit alignment restrictions internally

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#488]
The GNI provider needs to hide some of the alignment restrictions of the Aries hw unit, in particular, the dword alignment restrictions for FMA gets.  

Assigning to @ztiffany since he's most familiar with gni rma code.

**Comment by ztiffany** [comment]
Alignment issues and solution proposed:
send/recv: rendezvous sends need target addr, length 4 byte aligned
   -send head and tail in rendezvous control message, pull aligned data
RMA reads: need target addr, length 4 byte aligned
   -pull aligned target into user buffer
   -pull head/tail into a temporary buffer

AMOs: target addr/length need alignment to datatype size
AMO reads: source address also needs alignment to datatype size
   -Return -FI_EOPNOTSUPP and document limitations
