### ISSUE TITLE
add method for controlling number of gnix_nics/ptag/rank

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#49]
We need a method for determining the maximum number of gnix_nic's that can be allocated for a given ptag/cookie for a rank on a node.  This will likely require querying the alps placement file via the alps_get_placement_info call to determine the number of ranks in the job.   This call also works using nativized slurm.  This along with querying GNI_GetJobResInfo should give a good guess at this maximum.   This approach doesn't take into account the possibility that children of the initial processes launched by apshepherd (or slurmd) are the ones making libfabric calls.

The numPesHere field in the alpsAppLayout_t structure reports the number of ranks started locally by the launcher daemon.

Work on this issue is gated by merging of #48 

@ztiffany 
@sungeunchoi

**Comment by sungeunchoi** [comment]
See my comments on PR #48 about single launcher process (similar to child processes scenario above).

**Comment by hppritcha** [comment]
This approach may not work for CCM.  Need to verify that we can use `alps_get_placement_info`  on the nodes when running under CCM.
