### ISSUE TITLE
rendezvous path needs to be able to handle GNI_RC_NOT_DONE in completer funcs

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#491]
Right now it does not appear that the rendezvous path correctly handles cases when GNI_SmsgSendWTag for control messages returns GNI_RC_NOT_DONE.  This results in the completer_fn's returning non success, and certain MPI applications to hang.

@kim-mcmahon fyi

**Comment by hppritcha** [comment]
An example of an MPI app that hangs owing to this problem is osu_bibw.

**Comment by ztiffany** [comment]
A request is kept on the send queue if it's send function fails.  It should stay there and sends should be retried until successful.  Is this not working?

In the case of SMSG, we would rely on the receiver doing progress to trigger SMSG credit return to avoid hangs.
