### ISSUE TITLE
Add fi_ext_gni.h to install include directory

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#532]

**Comment by sungeunchoi** [comment]
@hppritcha I'm assigning this to you, because you seemed to think that this got lost during the merge.

**Comment by hppritcha** [comment]
hmm... okay I"m having a hard time reproducing this.  This is using the suspect nightly tarball on ofi web site correct?

**Comment by sungeunchoi** [comment]
Yeah: https://www.openfabrics.org/downloads/ofiwg/nightly_tarballs/v1.2.x/libfabric-latest.tar.bz2

**Comment by sungeunchoi** [comment]
My bad.  I had a type-o in my script.
