### ISSUE TITLE
fi_getinfo does not return full set of capabilities

### ISSUE THREAD

**Issue by nenadv** [ofi-cray/libfabric-cray#551]
After providing hint of 0 for fi_info.caps on fi_getinfo() I get back a 0 for caps, instead of bits for all supported capabilities.

**Comment by ztiffany** [comment]
This seems to be working based on output from the fi_info utility:

## tiger$ srun -n 1 util/./fi_info  -p gni -v

fi_info:
    caps: [ FI_SOURCE, FI_DIRECTED_RECV, FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_FENCE, FI_INJECT, FI_TRANSMIT_COMPLETE ]
...

**Comment by hppritcha** [comment]
I verified on upstream master that I get the same output from fi_info.

**Comment by hppritcha** [comment]
@nenadv could you double check?

**Comment by hppritcha** [comment]
I think this issue can be closed.

**Comment by chuckfossen** [comment]
srun -n 1 util/fi_info -p gni -v -c 0
...
fi_info:
caps: [  ]
