### ISSUE TITLE
gni provider doesn't make match if TX and RX sizes differ

### ISSUE THREAD

**Issue by kim-mcmahon** [ofi-cray/libfabric-cray#560]
I believe I've found a bug in the GNI-provider.  I've narrowed this down to a simple 2P MPI test case.  This works with the TCP-provider and hangs with the GNI-provider.

It appears that the fi_trecvmsg() function won't match an incoming message if the posted receive buffer is larger than the incoming send data buffer.

In my case I'm sending a 16384-byte message (via fi_tsend), and want to receive it by posting a 32768-byte receive buffer (via fi_trecvmsg).  The TCP provider makes the match, but the GNI provider doesn't.

It appears that size matter here.

For GNI, when I send that 16384-byte message, if I post a 19284-byte receive buffer, the match works, but if I post a 19334-byte receive buffer (or any larger size), it won't make the match.

For TCP, it will always make the match.

-Kim McMahon

**Comment by hppritcha** [comment]
this appears to be a tag match problem.  The tag matcher should only be checking if the send is larger than the receive buffer.

**Comment by ztiffany** [comment]
Request length is not a parameter to the matching engine.  I think the problem has to do with rendezvous sends where the send buffer is smaller than the receive buffer, and the receive buffer is an unaligned length.

req->msg. recv_len is always used for the transfer length in __gnix_rndzv_req().  If the receive buffer length is not aligned, the rendezvous get fails with an alignment error and the request will be hung.  We should be checking which buffer is shorter (send or recv) and use the appropriate length.  Additionally, if the receive buffer is shorter and unaligned, we'll need to do a separate GET to move unaligned data.
