### ISSUE TITLE
gni provider does not build from the nightly tarball

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#574]
make[1]: **\* No rule to make target `man/man7/fi_gni.7', needed by`all-am'.

**Comment by hppritcha** [comment]
@sungeunchoi this is after the most recent merge from upstream? HEAD == e504dfa6d0dabc918151ef055dbc320d2e73aea3

**Comment by sungeunchoi** [comment]
This is from the latest tarball build (nightly jenkins test).

**Comment by sungeunchoi** [comment]
https://www.openfabrics.org/downloads/ofiwg/nightly_tarballs/v1.2.x/libfabric-latest.tar.bz2

**Comment by hppritcha** [comment]
hmmmm.. if I build the tarball on a vanilla whitebox that only can build sockets provider, I only get man7/fi_sockets.7 in the tarball.

**Comment by hppritcha** [comment]
i have an automake change for our provider makefile that will fix this.  we can wedge it in now.

**Comment by sungeunchoi** [comment]
Did you see Jeff's email.  He's working on something also related to https://github.com/ofiwg/libfabric/pull/1558/files

**Comment by sungeunchoi** [comment]
Fixed by https://github.com/ofiwg/libfabric/pull/1558
