### ISSUE TITLE
Fix initialization of gnix_id_counter.

### ISSUE THREAD

**Issue by bturrubiates** [ofi-cray/libfabric-cray#58]
In #57 I fixed a bunch of atomic_t initialization issues. gnix_id_counter was defined as a static global. I have now changed it so that it is defined as extern in gnix.h and initialized in gnix_fabric.c in the INI function. I'm not sure what the correct way to initialize it is, but one might be using a pthread_mutex directly and using a static initializer.

**Comment by hppritcha** [comment]
Danish seems to know how to do this.
