### ISSUE TITLE
OSU tests issues

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#584]
- osu_mbw_mr FAILED (-n16 -N2 -t00:2:00)
- osu_mbw_mr FAILED (-n32 -N2 -t00:2:00)
- osu_multi_lat FAILED (-n16 -N2 -t00:2:00)
- osu_multi_lat FAILED (-n32 -N2 -t00:2:00)
- osu_barrier FAILED (-n4 -N2 -t00:2:00 --exclusive)

Plus one warning "Insufficient network resources" and many "failed to fully close domain due to lingering references".

**Comment by hppritcha** [comment]
These failures are related to #587

**Comment by sungeunchoi** [comment]
I added the --exclusive option to my script for now.
