### ISSUE TITLE
rdm_rma tests warn about failing to close a few domains when FI_LOG_LEVEL=warn

### ISSUE THREAD

**Issue by e-harvey** [ofi-cray/libfabric-cray#592]
Closing a domain without closing the objects that hold a reference to the domain may cause this error.  The domain should be closed when the last object holding a reference to the domain is closed.

**Comment by e-harvey** [comment]
The following tests throw "failed to fully close domain due to lingering references." warnings: `rdm_rma::inject_write`, 
`rdm_rma::inject_write_retrans`, 
`rdm_rma::inject_writedata`,
`rdm_rma::inject_writedata_retrans`,
`rdm_tagged_sr::tinject`,
`rdm_atomic::atomicinject`.

The rdm_rma tests appear to be leaving references due to `_gnix_fr_free` not being called in `gnix_rma.c:_gnix_rma`.  However, when calling `_gnix_fr_free` every time in `gnix_rma.c:_gnix_rma` some rdm_rma tests such as `inject_write_retrans` hangs while others such as `inject_write` pass with no lingering references.

**Comment by sungeunchoi** [comment]
These were determined to be benign, as the progress thread is still cleaning up fab reqs.  #628 changed the GNIX_WARN to GNIX_INFO (to be consistent), so we don't see these any more.
