### ISSUE TITLE
Add short-circuit of log messages in GNIX_LOG_INTERNAL

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#596]

**Comment by jswaro** [comment]
Prior to fix:

> Using local file tester.
> Using local file /home/users/jswaro/test.out_16636.
> Total: 4432 samples
>    1587  35.8%  35.8%     2764  62.4% _IO_vfprintf_internal
>     640  14.4%  50.2%      693  15.6% _IO_default_xsputn_internal
>     384   8.7%  58.9%      384   8.7% __strchrnul
>     212   4.8%  63.7%     3407  76.9% _IO_vsnprintf
>     145   3.3%  67.0%      221   5.0% _IO_str_init_static_internal
>     143   3.2%  70.2%      143   3.2% _IO_old_init
>     137   3.1%  73.3%      137   3.1% fi_log_enabled_

Timing:

> real   0m20.024s
> user   0m0.008s
> sys    0m0.016s

**Comment by jswaro** [comment]
After patch:

> Using local file tester.
> Using local file /home/users/jswaro/test.out_16741.
> Total: 495 samples
>     108  21.8%  21.8%      287  58.0% gnix_mr_reg
>      70  14.1%  36.0%       70  14.1% fi_log_enabled_
>      64  12.9%  48.9%      183  37.0% fi_gnix_mr_close
>      58  11.7%  60.6%       58  11.7% pthread_spin_lock
>      52  10.5%  71.1%       94  19.0% __mr_cache_search_inuse.isra.8.constprop.12
>      37   7.5%  78.6%       41   8.3% __mr_cache_entry_put
>      17   3.4%  82.0%       17   3.4% __ioctl
>      14   2.8%  84.8%       75  15.2% __mr_cache_deregister (inline)
>      11   2.2%  87.1%       15   3.0% rbtFindLeftmost
>      10   2.0%  89.1%       10   2.0% _init

Timing:

> real   0m4.075s
> user   0m0.008s
> sys    0m0.012s
