### ISSUE TITLE
Implement fi_direct

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#600]

**Comment by ztiffany** [comment]
@sungeunchoi do you mean FI_DIRECT_RECV?  We do already support that one.

**Comment by hppritcha** [comment]
I think she means supporting fi_direct I.e. Hardwire  libfabric to bypass its usual invocation of provider methods using pointers to functions and instead invoke the gni provider methods directly.

This may help on KNL.

**Comment by sungeunchoi** [comment]
Yes. I mean fi_direct (http://ofiwg.github.io/libfabric/master/man/fi_direct.7.html).
