### ISSUE TITLE
Optimize tag storage

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#603]
The tag matching engine currently stores tags in a linked list giving us O(n) lookup of tags.  It should be improved to use a better data structure for faster lookups.

**Comment by jswaro** [comment]
There was a discussion for two additional data structures, a hash table
and a hybrid structure. The hash table should be somewhat trivial to
implement, but for proper operation, the ignore bits will require us to
search multiple buckets. The hybrid structure may not be needed still, but
presents an opportunity for improvement over both structures.
-- Jim
