### ISSUE TITLE
Intermittent hang in rdm_sr/sendrecv_alignment

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#606]
rdm_sr/sendrecv_alignment will usually hang within 10 attempts on tiger.  Changing the GNI provider to use FI_PROGRESS_MANUAL as the data progress default seems to fix this.

```
--- a/prov/gni/src/gnix_fabric.c
+++ b/prov/gni/src/gnix_fabric.c
@@ -166,7 +166,7 @@ static int gnix_getinfo(uint32_t version, const char *node, const char *service,
        int ret = 0;
        uint64_t mode = GNIX_FAB_MODES;
        enum fi_progress control_progress = FI_PROGRESS_AUTO;
-       enum fi_progress data_progress = FI_PROGRESS_AUTO;
+       enum fi_progress data_progress = FI_PROGRESS_MANUAL;
```

**Comment by ztiffany** [comment]
@hppritcha

**Comment by sungeunchoi** [comment]
@hppritcha 
Should we do this for all the tests for now and explicitly add tests for auto progress?

**Comment by hppritcha** [comment]
You mean run the `gnitest` several times?  Note the default data progress is `FI_PROGRESS_AUTO`.

**Comment by hppritcha** [comment]
I'm seeing how easy I can reproduce this.

**Comment by sungeunchoi** [comment]
Also, is this possibly the same problem as #592 ?

**Comment by hppritcha** [comment]
I don't think this problem is related to #592.

**Comment by sungeunchoi** [comment]
Actually I was thinking about the valgrind hangs that I reported on the tests that used multiple domains.  I guess I never opened an issue about that.  Will gather more info and see if it's related.

**Comment by hppritcha** [comment]
Those problems were seen prior to PR #589 which first introduced progress for data.
