### ISSUE TITLE
Implement fi_tx_size_left()/fi_rx_size_left() interfaces

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#637]
The GNI provider should never fail to post a TX or RX unless perhaps we run out of memory.  These interfaces should return a minimum number of requests that can be posted without error.  Maybe they should return some arbitrarily large but not memory stressing value?

**Comment by sungeunchoi** [comment]
Another option would be to have a provider-specific version that returns some recommended high watermark if such a thing exists.  I'm not sure how I feel about using these precise functions for that based on the man page:

```
Depending on the specific details of the subsequently posted receive operations (e.g., number
of iov entries, which receive function is called, etc.), it may be possible to post more receive
operations than originally indicated by fi_rx_size_left.
```

If the client knew that there were no limit, they might choose to behave differently.

**Comment by ztiffany** [comment]
@sungeunchoi the man pages say xx_size_left() is supposed to return a low water mark, not a maximum.

**Comment by sungeunchoi** [comment]
So would the "arbitrarily large, but not memory stressing value" you're proposing actually provide meaningful guidance to the client?  Or would it just be something to return so as not to hinder the client code unnecessarily?

**Comment by ztiffany** [comment]
Yes, some number that satisfies both the of:

-More requests than any client would need
-Less requests than would consume all memory on our typical machines

Nothing practical would create TXs until all memory was gone, but that's reason to not use something approximating infinite like UINT64_MAX.  64, 128, 1024?  All those seem reasonable.
