### ISSUE TITLE
Implement DGRAM endpoint type

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#638]
DGRAM endpoints are similar to RDM except not reliable.  With RDM endpoints mostly done, it may be easy to support DGRAM EPs for all the same functionality.

Should we disable any internal retransmission attempts when using DGRAM vs RDM?

**Comment by hppritcha** [comment]
yes let's drop packets!

**Comment by sungeunchoi** [comment]
Being a bit unreliable myself, I'm all for it!  I would guess that the overhead for disabling retransmission in RDM is fairly low, but speak up if you think otherwise.
