### ISSUE TITLE
Implement MSG EPs

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#639]
MSG EPs are a good fit for socket like consumers.  A MSG endpoint represents a single connection.  Implementation of this feature would involve finishing passive endpoints, EQs for connection management and the connection management API (fi_accept(), fi_connect(), etc.).

**Comment by sungeunchoi** [comment]
- fi_passive_ep
- fi_pep_bind
- fi_setname
- fi_listen
- fi_accept
- fi_reject
- fi_shutdown

**Comment by ztiffany** [comment]
Decouple gnix_cm_nic and fi_domain.  A CM NIC is needed in a PEP.

**Comment by hppritcha** [comment]
@sungeunchoi can this issue be close?

**Comment by sungeunchoi** [comment]
Yeah -- let's close it, and track this through #1109 and #1208.
