### ISSUE TITLE
Implement memory registration callbacks

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/libfabric-cray#657]
To support XPMEM and normal registration, the cache should provide registration and deregistration callbacks.

@hppritcha

**Comment by jswaro** [comment]
@hppritcha

**Comment by hppritcha** [comment]
What I would like to do for the current memory registration cache is add the following new fields to the `gnix_mr_cache_attr_t` struct:

```
    void *mem_reg_ctx;
    void *mem_dereg_ctx;
    void *cache_destroy_ctx;
    void *(*mem_reg_callback)(void *base_addr, size_t len, void *ctx);
    int (*mem_dereg_callback)(void *, void *ctx);
    int (*cache_destroy_callback(void *ctx);
```

The consumer of the memory registration cache functionality would set the pointers to the 3 different ctx's. as part of the `gnix_mr_cache_attr_t`, along with pointers to callback functions.  The `mem_reg_callback` returns a pointer to an opaque object which the mem reg cache associates with the cache entry tracking the `base_addr/len``.  This in turns ends up being the``void *``argument to the``mem_dereg_callback`` function.  

The `cache_destroy_callback` is invoked when `_gnix_mr_cache_destroy` is invoked by the consumer of the mem reg cache functionality.

The memory registration cache is responsible for any rounding down/up to account for large pages, etc, prior to invoking the `mem_reg_callback` function.

With these changes, the GNI specific memory registration code can be pulled out of gnix_mr.c and moved somewhere else, likely into gnix_dom.c

**Comment by jswaro** [comment]
So that I completely understand where you are going with this...

You want the following?

``` C
static inline int __mr_cache_entry_destroy(
        gnix_mr_cache_entry_t *entry)
{
    gni_return_t ret;

    fastlock_acquire(&entry->nic->lock);
    ret = cache->dereg_callback(entry, cache->attr.dereg_context);
    fastlock_release(&entry->nic->lock);
```

instead of 

``` C
static inline int __mr_cache_entry_destroy(
        gnix_mr_cache_entry_t *entry)
{
    gni_return_t ret;

    fastlock_acquire(&entry->nic->lock);
    ret = GNI_MemDeregister(entry->nic->gni_nic_hndl, &entry->mem_hndl);
    fastlock_release(&entry->nic->lock);
```

Or did you want the the callback to execute after the dereg?

If the purpose is to generalize the cache, more work may be necessary than just adding the callbacks. The cache is fairly tightly coupled with gnix.

**Comment by hppritcha** [comment]
almost, something like

``` C
static inline int __mr_cache_entry_destroy(
        gnix_mr_cache_entry_t *entry)
{
    gni_return_t ret;

    fastlock_acquire(&entry->nic->lock);
    ret = cache->dereg_callback(entry->ptr-to-void-star-return-from-reg-callback, 
cache->attr.dereg_context);
    fastlock_release(&entry->nic->lock);
```

**Comment by jswaro** [comment]
And how would the context be appropriately populated to contain the
information relevant to the registration? From a libfabric perspective,
the nic isn't known in advance, and there may be many nic's associated
with a given domain.

What doesn't make sense to me is what type of abstraction this is. Is this
a provider-abstraction where we are removing the device-specific
information but still passing the libfabric information along?
-- Jim

**Comment by hppritcha** [comment]
I was thinking the context provided to the mem_reg/dereg would be a pointer to `gnix_fid_domain`.

The abstraction I'm going for is that of the cache itself.  The functionality provided in gnix_mr.c to implement the libfabric mr functionality would use the mr cache with the callbacks much as you have embedded now in the mem reg. cache code.  What I would like to see is the cache separated out from the libfabric functionality.

There would be a special, internal use of the registration cache to handle xpmem.  Since the app already has to supply the vaddrs to be used for fi_read/write etc. the xpmem doesn't really need the `fi_mr_key.`

I realize now that we'd need another callback that implements the fi_mr_key abstraction.  That would be used in place of  `_gnix_convert_mhdl_to_key`.

Does this make sense?
