### ISSUE TITLE
osu_alltoallv using craypich/ofi netmod hangs periodically

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#661]
@kim-mcmahon reported that she still sees occasional hangs for osu_alltoallv when linked against craypich/ofi netmod.

Per the readme she supplied

```

1. SET this two env variables

export MPICH_NEMESIS_NETMOD=ofi
export MPIR_CVAR_OFI_USE_PROVIDER=gni


2. Put the following in a loop and run on tiger

srun -n 64 --ntasks-per-node=8 --exclusive ./osu_alltoallv
```

this is on tiger.

**Comment by sungeunchoi** [comment]
Update: all the progress threads seem to be hung shortly after starting (likely in GNI_CqVectorMonitor).

**Comment by hppritcha** [comment]
Note there is more than one progress thread.  There is a thread per `gnix_nic` and these do block in a call  to `GNI_CqVectorMonitor` if data_progress is not set to `FI_CONTROL_MANUAL`.  There is also one thread per `gnix_fid_domain` that is blocked waiting for kGNI dgrams.  It should be blocked in `GNI_PostdataProbeWaitById` if control_progress is not set to `FI_CONTROL_MANUAL`.

**Comment by sungeunchoi** [comment]
The other progress thread I see looks stuck `__process_datagram` via `_gnix_dgram_poll`, similar to the progress threads in valgrind hangs in #653.

**Comment by sungeunchoi** [comment]
The most common failure is due to `GNI_EpPostDataWId` returning GNI_RC_INVALID_PARAM.  According to Tony, this can indicate that a datagram is already in progress, which seems the most likely scenario, since the ep and datagram id passed in looked good.

I got a custom ugni library from Tony and confirmed that when we saw the above, there was in fact another datagram in flight.

**Comment by hppritcha** [comment]
I still see very occasionally see hangs (1 out of 50 runs using formula at the top of this issue) when I have  control_progress `FI_PROGRESS_AUTO`.  The signature is that no alltoallv trans lens are printed to stdout.  With lgdb, I see most ranks waiting in the first barrier (line 137) after the alltoallv  call (line 128). 
This is with #682 and #679.

If I disable auto-progress for control, the hang does not seem to occur (100s of runs of the test and no hang).

**Comment by hppritcha** [comment]
Adding more debugging, it appears that for some reason, one of the EPs doesn't move all VC's to connected state.  This leads to the hang in the alltoallv for two ranks.
