### ISSUE TITLE
fi_av_straddr isn't correct

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#665]
Discussions on the user list indicate that the current GNI provider isn't implementing fi_av_straddr
completely correct.  The function needs to actually contain both the `gnix_addr` field as well as the contents of the `struct` containing `type`, etc.   

``` C
struct gnix_ep_name {
¬       struct gnix_address gnix_addr;
¬       struct {
¬       ¬       uint32_t name_type : 8;
¬       ¬       uint32_t cm_nic_cdm_id : 24;
¬       ¬       uint32_t cookie;
¬       };
¬       uint64_t reserved[4];
};
```

**Comment by tonyzinger** [comment]
Currently the gnix_av_straddr() writes the device_addr and cdm_id into the string buffer as 2 hex values separated by a ':'.

Should the new string value be "device_addr:com_id:name_type:cm_nic_cdm_id:cookie"?
Where, the device_addr, com_id, cm_nic_cdm_id and cookie values would be hex values and the name_type would be an int value.

Is this the correct ordering of these values?

**Comment by hppritcha** [comment]
I think your proposed syntax should work fine.  I think to keep things simple, use this for the output for
`fi_ep_getname` function as well.  Using `:` between the fields is a good idea.  It will help going forward if we have to add new fields to the name/straddr output.

**Comment by tonyzinger** [comment]
I cannot find the function, fi_ep_getname.  Do you mean fi_getname? fi_getname() calls gnix_getname().  In gnix_getname(), it copies the gnix_ep_name structure not a string created by gnix_av_straddr().
What am I missing?

Also, I noticed that the straddr_test() in prov/git/test/av.c does not verify very much.  The cr_assert_eq(buf, address) is comparing itself.  the fi_av_straddr returns the address pointer back as buf. So this comparison is comparing the contents of the same address, which will never fail.

**Comment by hppritcha** [comment]
You're right about the gnix_getname.  I think it would be simplest to have it simply call the `gnix_av_straddr` and let it allocate the properly formatted name (the one you've proposed with the ":" 's).  

Then, you'd want to modify the code in gnix_av.c around lines 163-169 and 288-295 to crack the string to pull out the `gnix_addr`, `name_type`, `cm_nic_cdm_id`, and `cookie` fields.

Yes the criterion test is somewhat lame.  You'd probably want to compare the contents of the string you'll be creating with the ":" 's with the fields in the `gnix_fid_ep` 's `my_name` contents.

Does this make sense?

**Comment by tonyzinger** [comment]
Do I need to change gnix_av_lookup()?

The fabtests are failing.  For example, fi_av_test2 -f gni
Process 0 return value: 0
=== OUTPUT ===
fi_av wrong answer

The av_test2.c has this code when it prints the above error message:
    test_name_addr = malloc(test_addrlen);
    assert(test_name_addr != NULL);

```
ret = fi_av_lookup(av, remote_fi_addr, test_name_addr, &test_addrlen);
if (ret != FI_SUCCESS) {
    fprintf(stderr,"fi_av_lookup %d: %s\n", ret, fi_strerror(-ret));
    goto err;
}

if (memcmp(local_name_addr, test_name_addr, test_addrlen)) {
    fprintf(stderr,"fi_av wrong answer\n");
    ret = -FI_EINVAL;
    goto err;
}
```

**Comment by hppritcha** [comment]
@tonyzinger Yes this function needs to be modified to.  The tet_name_addr buffer should get the same
string returned as fi_av_straddr
