### ISSUE TITLE
improve method for generating unique cdm_id's for GNI_CdmCreate

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#693]
Currently the cdm_id's supplied to `GNI_CdmCreate` make use of the 16 LSBs of the process which opens the libfabric domain object.  The 16 MSBs are then generated using a static variable.  This method can run in to problems across a fork operation and possibly other edge cases.  

A better method might involve something like a file in /var/tmp who's content would be an integer that is read and updated by processes when they need to obtain a unique cdm id as part of the `gnix_nic_alloc`, etc.  The name of the file could be based off of a node/job wide constant like the RDMA credentials value (the `cookie` supplied to calls to `GNI_CdmCreate`).

**Comment by jswaro** [comment]
A simple solution perhaps: pthread_atfork()? 

Set up a child handler to re-assign the value of the pid ID after fork by calling getuid()

**Comment by hppritcha** [comment]
fixed by #689
