### ISSUE TITLE
Fix warnings when compiling with -Werror and FI_DIRECT

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#697]
In file included from prov/gni/src/gnix_atomic.c:38:0:
./prov/gni/include/gnix.h:803:5: error: "FABRIC_DIRECT_ENABLED" is not defined [-Werror=undef]
 #if FABRIC_DIRECT_ENABLED
     ^
cc1: all warnings being treated as errors

**Comment by e-harvey** [comment]
This was address by #698.
