### ISSUE TITLE
gnixu_get_pe_from_ip fails for nodes with Xeon Phis

### ISSUE THREAD

**Issue by tschuett** [ofi-cray/libfabric-cray#706]
Hi,

I am using libfabric on a Cray with Xeon Phis and gnixu_get_pe_from_ip fails. I am not trying to run libfabric on the Phis. The problem is on the host cpu.

On the host, the IP address is assigned to ipogif0 and br0.  When gnixu_get_pe_from_ip scans /proc/net/arp for the ip address, it also checks whether line contains "ipogif". That last part fails. Here is an example line from /proc/net/arp:

`10.128.0.2       0x1         0x6         00:01:01:00:00:01     *        br0`

**Comment by hppritcha** [comment]
Thanks for reporting this.   We'll fix this in time for the 1.3 release.  Are you able to patch for your system?

**Comment by tschuett** [comment]
Sure. No problem. I simply replaced the "ipogif" by "br".
