### ISSUE TITLE
fi_rdm_pingpong sometimes seg faults when run without --exclusive

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#723]

**Comment by hppritcha** [comment]
How often does this occur?

**Comment by sungeunchoi** [comment]
@ztiffany saw it pretty easily.  Also, I should write that it periodically seg faults even with --exclusive.  It's on exit, and I'm wondering if it's similar to #709

**Comment by hppritcha** [comment]
should have a fix for this tomorrow.  unfortunately its not relevant to all the mpich osu failures.
