### ISSUE TITLE
VC outstanding_tx_reqs goes out of sync after transfer fails due to insufficient caps

### ISSUE THREAD

**Issue by ztiffany** [ofi-cray/libfabric-cray#728]
Atomic and RMA TX callbacks can fail due to insufficient capabilities at the target node.  In this case, an error event is created and the fabric request is freed inside the TX callback.  FI_SUCCESS is then returned to from the TX callback, causing the request to be removed from the VCs TX queue and the outstanding_tx_reqs count being incremented.  The outstanding_tx_reqs count would never be decremented for such a request.  Additionally, the request is freed before it is removed from the VCs TX queue, corrupting the requests list entry (which is also used in the freelist implementation).

**Comment by hppritcha** [comment]
@ztiffany is this still relevant after your vc refactor.
