### ISSUE TITLE
GNI provider should support iov_limit > 1

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#729]
In beginning work on a BTL component for Open MPI (partly to support MPI-3 RMA as well as allowing for use of libfabric in situations where tag matching by libfabric is not desired), its become apparent that without at least support for iov_limit == 2,  there will need to be a lot of packing of messages on the send side.  This is due to the fact that the usage model for sends in the BTL framework of Open MPI is to send a header + payload, where payload is typically the actually application message data, and the header is Open MPI protocol specific info.

It looks like the PSM (but not PSM2) and GNI providers have the limitation of iov_limit == 1.  Can't tell about usnic.

**Comment by sungeunchoi** [comment]
From the fi_msg man page regarding fi_sendv (and fi_tsendv):

"The fi_sendv transfers the set of data buffers referenced by the iov parameter to a remote endpoint as a single message."

A strict interpretation of this would require the GNI provider to copy the data into a single buffer.

**Comment by sungeunchoi** [comment]
In talking to others, it appears that other providers have not used a strict interpretation of the man page.  I think the goal should be to have better performance than individual messages.  Eventually this may lead to multiple internal implementations that can be selected either automatically or by the user.

**Comment by e-harvey** [comment]
The GNI provider still needs to implement fi_readv and fi_writev before this issue will be resolved.
