### ISSUE TITLE
need a function to keep  cray job container/core spec happy

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#74]
The libfabric gni provider is going to use a bunch of threads that are not application threads.  One thread to call  `GNI_WaitErrorEvents`, and most likely one per FID_RDM_EP type endpoint to handle incoming datagram connection requests.  

The functionality we need is two fold:
- a method to write to /proc/job "disable_affinity_apply" string so that job container knows next thread created in the process space of the thread that wrote this string should not go through the cray job containers thread pinning algorithm
- to help with core spec, the spawned thread needs a method to write "0" into `/proc/self/task/tid/task_is_app` 

Dean Roe can help with this.
@jswaro 
@sungeunchoi

**Comment by sungeunchoi** [comment]
@ztiffany

**Comment by hppritcha** [comment]
These functions probably should go in the gnix_util.c for now.
