### ISSUE TITLE
GNI provider not showing FI_EP_DGRAM info from fi_info

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#747]
Looks like we may have some missing support for FI_EP_DGRAM.  The output from the fi_info command only shows a single info struct being returned, that for FI_EP_RDM.  We should be returning an info struct for both endpoint types.

**Comment by chuckfossen** [comment]
~~Shouldn't we also be supporting FI_EP_MSG as well?~~ Never mind. I see that we don't support MSG yet.
