### ISSUE TITLE
Set up regular Coverity scans

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#76]

**Comment by sungeunchoi** [comment]
Ran initial scan, but it failed because only 7% of the code base was compiled.  In contact with scan-admin for assistance.

**Comment by jswaro** [comment]
Is this resolved?

**Comment by sungeunchoi** [comment]
This should be closed.  Coverity does not do scans on forks of github projects, so we are out of luck.
