### ISSUE TITLE
Add wiki example for "Day in the life of a message"

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#78]

**Comment by hppritcha** [comment]
would like to get power point animations in github wiki friendly format.
Meanwhile just put pdf/ppt up on wiki.

**Comment by jswaro** [comment]
This is already complete right?

**Comment by hppritcha** [comment]
no, it still needs to be filled in on the wiki

**Comment by hppritcha** [comment]
this document has been added to the wiki.
