### ISSUE TITLE
Add growable bit map implementation

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#79]

**Comment by hppritcha** [comment]
The bitmap implementation can be used in a couple of places in the GNI provider.  One is for the table of 
`gnix_vc`'s structs when the AV associated with a given RDM EP is using the FI_AV_TABLE type.  A very large  table of VCs backed by an mmap'd ANON region could be sparsely faulted in, using the bitmap as a guide to whether or not a vc struct in the mmap region needs to be initialized.

Another, more important place where such a bitmap will be needed is in handling of GNI RX CQ overruns.
Using a bitmap to track which mboxes are active can accelerate polling over mail boxes looking new messages when the RX CQ is overrun. 

For the second,  it is important that the scanning of the bitmap for set bits be efficient.    Its not known how often MPI applications currently hit this RX overrun condition.

**Comment by jswaro** [comment]
I need to clarify something here. By growable, do you mean that we should be able to realloc() the bitmap to make it larger if need be, or that it must be size independent? So far, I'm assuming the former rather than the latter.

**Comment by jswaro** [comment]
Will it be safe to assume that we aren't going to do something silly like grow the bitmap while at the same time trying to read from it?

**Comment by bturrubiates** [comment]
Well since this is intended to be a parallel data structure it would be hard to make assumptions about what one thread might be doing at any given time. I think it's best to enforce some kind of locking policy when doing some operation that involves large mutations like a realloc.

**Comment by hppritcha** [comment]
I think for the places we will use the bitmap in the provider we can do without locking in the bitmap code.

**Comment by jswaro** [comment]
@hppritcha 
I'll remove the locking code.

**Comment by jswaro** [comment]
> ./gnitest --pattern 'gnix_bitmap*'
> [====] Synthesis: 79 tests were run. 41 passed, 0 failed (with 0 crashes)

I'm going to package it up.
