### ISSUE TITLE
Add lockless calls to the gnix_bitmap functions

### ISSUE THREAD

**Issue by e-harvey** [ofi-cray/libfabric-cray#794]
The buddy allocator currently uses the bitmap to track allocated and split blocks but the allocator locks before allocating or freeing blocks.  Since the bitmap provides atomic operations only, the locks being acquired and released within the bitmap are a waste of resources, in the case of the current implementation of the buddy allocator this is wasteful particularly for coalescing.

**Comment by jswaro** [comment]
This should be closed as invalid. The locks are only used when atomics are not available. This atomic availability is checked at compile time, so no locks would be present if we truly do have atomics. 

@sungeunchoi I'm going to close this unless you object.

**Comment by hppritcha** [comment]
finally closing
