### ISSUE TITLE
Write a simple criterion test that calls fi_tsend/fi_trecv in a loop on a single rank

### ISSUE THREAD

**Issue by e-harvey** [ofi-cray/libfabric-cray#802]

**Comment by jswaro** [comment]
What is the purpose of such a test?

**Comment by e-harvey** [comment]
This test is supposed to help us look at ping pong latency.  However, this test could just be written with a main function as an entry point in gni/contrib without any criterion specific calls.  Any thoughts?

Evan

**Comment by e-harvey** [comment]
@sungeunchoi. @hppritcha Is this something you would still like me to do?

**Comment by hppritcha** [comment]
I would like such a perf micro benchmark test, yes.

**Comment by e-harvey** [comment]
It looks like https://github.com/ofi-cray/cray-tests/blob/master/performance/multi-node/rdm_pingpong.c does this.  Closing.
