### ISSUE TITLE
api_cq/msg crashes periodically during teardown

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#819]
The api_cq/msg test reports the following warning and then crashes:

```
libfabric:gni:ep_data:__nic_get_completed_txd():464<warn> [5005:1] CQ error status: SOURCE_SSID:AT_PF_INV:CPLTN_DREQ
[----] Warning! The test `api_cq::msg` crashed during its setup or teardown.
```

I was able to repro about 1 in 5 tries.  Unfortunately criterion does not report it as failing or crashing, so it's easy to miss.  Not sure how long it's been there.

**Comment by sungeunchoi** [comment]
This happens reliably in CCM-mode.

**Comment by sungeunchoi** [comment]
Since I just saw it, wanted to update to say that I still see the crash, but it seems less frequent.  I have not seen the CQ error warning.

**Comment by sungeunchoi** [comment]
This might be fixed with #1134

**Comment by chuckfossen** [comment]
Still happening with #1134

**Comment by jshimek** [comment]
@chuckfossen Can we close this issue now, or is it not fixed with your commit?
