### ISSUE TITLE
AV map assumes multiple inserted entries will be remove together

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#839]
If inserting with count > 1, the implementation assumes that the entries will be removed in a similar fashion.

**Comment by jswaro** [comment]
Are the addresses also being added in block fashion or 1-by-1?

**Comment by sungeunchoi** [comment]
Block-fashion

**Comment by jswaro** [comment]
Is this still an issue? It looks to me that the entries are being inserted individually. 

gnix_av.c:master(as of 12/13/2016)
https://github.com/ofi-cray/libfabric-cray/blob/cf679cc/prov/gni/src/gnix_av.c

**Comment by sungeunchoi** [comment]
But the individual items are allocated out of a single block, so I don't think you can ever free them properly.  How does the freeing work in this case?

**Comment by jswaro** [comment]
The HT only holds a pointer reference to the block. The block is freed on AV destruct, so memory isn't being leaked. This particular implementation may not be very efficient from a memory use perspective, but it doesn't appear to be bugged. Individual entries can be removed, but they still remain in the block until the AV is destroyed, effectively wasting space but not doing anything harmful.

It doesn't appear to be any different from how AV table behaves except that the AV map entries can be stored in virtually dis-contiguous space.

**Comment by sungeunchoi** [comment]
You're right.  This is a problem for the client.
