### ISSUE TITLE
Set and check the CQE buf field properly

### ISSUE THREAD

**Issue by e-harvey** [ofi-cray/libfabric-cray#876]
Currently in rdm sr gnitests, the CQE buf is asserted to equal the user's destination buffer when the FI_MULTI_RECV flag _is not_ set but the man page specifies that this condition only applies when the FI_MULTI_RECV flag _is_ set.

The rdm sr tests should assert the following:
`if (flags & FI_MULTI_RECV)
assert(cqe->buf == dest)
else
assert(cqe->buf == NULL)`

The code in gnix_msg.c should do the following:
`if (flags & FI_MULTI_RECV) cqe->buf = recv_addr else cqe->buf = NULL`

**Comment by hppritcha** [comment]
The suggestion for the check in rdm_sr isn't exactly right.  FI_MULTI_RECV should not be returned in the CQE flags except when there is no more room in the multi-recv buffer to receive new messages.
