### ISSUE TITLE
Document workflow and policies on Wiki

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#9]

**Comment by bturrubiates** [comment]
Definitely things to add to the workflow policy:
- The linux style guide script. Link to your script and provide instructions for setting up the hook.
- Recommend the [pro git](http://git-scm.com/book/en/v2) book. It is one of the best books for learning git and is also free to read online.

I think it'd be helpful for us to start an issue heavy workflow. Anytime that a fix/feature is going to be added it must contain an issue. The closes tag can then be used in the pull request to make sure that it is automatically resolved.

I said most of this in the conference call, but I figure I should write it out here before forgetting. :+1: 

@sungeunchoi Are you still going to take this issue?

**Comment by sungeunchoi** [comment]
Yup.  I've got this.

**Comment by bturrubiates** [comment]
:+1:
