### ISSUE TITLE
naming convention for gni provider internal functions

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#91]
Discuss a naming convention for gni provider functions used only internally.  Should this apply for both functions that need global visibility within the provider, and for static functions used only internally in a single file?

**Comment by hppritcha** [comment]
Assignee will come up with a proposal and document on the wiki.

**Comment by bturrubiates** [comment]
I don't think we have a set convention for static functions used only internally in a file. The other convention (_) applied to header exported internal functions. Should we also have a file local convention?

**Comment by hppritcha** [comment]
If it would help with readability of the code then I'd be fine with that.
But not to underscores though.  Maybe one before and one after the name?

2015-04-28 14:49 GMT-06:00 Ben Turrubiates notifications@github.com:

**Comment by jswaro** [comment]
@hppritcha , @sungeunchoi , @ztiffany 

Are we going with two underscores or prefix/suffix '_' for local file/variable declarations? Sung asked me to document our policy and I'd like to clarify this. I don't care personally, but the trailing '_' feels weird to me. It feels reminiscent of python internal/built-in function convention. I understand Howard's point as two leading underscores could be difficult to tell from a single underscore, which would make detecting scope a bit more difficult.

**Comment by hppritcha** [comment]
I'm not too particular (except for the trailing _ ) .  I started using the
`__` for static functions used only within a given file - except for
those functions which get plugged in to one of the many `ops` structs
used in libfabric.  I noticed we do have some variations though.

Let's discuss today.

Howard

2015-05-11 15:02 GMT-06:00 James Swaro notifications@github.com:
