### ISSUE TITLE
Investigate application hangs caused by using FI_AUTO_PROGRESS

### ISSUE THREAD

**Issue by e-harvey** [ofi-cray/libfabric-cray#910]
- There may be race conditions when using FI_AUTO_PROGRESS.

For more details and to reproduce the hangs, see #896.

**Comment by hppritcha** [comment]
OFI MTL in Open MPI by default uses manual progress for control and auto progress for data.

**Comment by hppritcha** [comment]
I'm taking this one.

**Comment by hppritcha** [comment]
I think this was fixed by #928
