### ISSUE TITLE
Could use an ops_open method which allows an EP to only use GNI_PostFMA

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#92]
Per discussions with compiler group, there's a request to allow for a provider specific extension to ensure that short write/read RMA ops go through the `GNI_PostFma` route rather than `GNI_PostRdma`.

**Comment by hppritcha** [comment]
Note that there is a size limits on Aries/gni for transfers using `GNI_PostFma`.  So this option is for advanced users of libfabric/GNI provider only.

**Comment by ztiffany** [comment]
The RMA RDMA threshold can be set with the GNI_RMA_RDMA_THRESHOLD ops value, like:

```
                ret = fi_open_ops(&domain->fid, FI_GNI_DOMAIN_OPS_1,
                                  0, gni_domain_ops, NULL);

                ret = gni_domain_ops[i]->set_val(&domain->fid,
                                                 GNI_RMA_RDMA_THRESHOLD,
                                                 &thresh);
```

See fi_gni.7.
