### ISSUE TITLE
vc connect to self algorithm doesn't work with FI_AV_TABLE type

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#930]
The code involved in vc connect to self doesn't work for FI_AV_TABLE type because
the insertion in to the ep's vc table (`_gnix_ep_vc_store`) uses the ep's name,
not taking in to account that the store could be using an index (FI_AV_TABLE).

This was discovered running some Open MPI regression tests with FI_AV_TABLE type.

**Comment by ztiffany** [comment]
This is the same as issue #984.
