### ISSUE TITLE
Up API version (fi_version) for GNI provider

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#936]
Once ofiwg/libfabric#2279 is merged in upstream we should up `fi_version` in the GNI provider.

**Comment by hppritcha** [comment]
@sungeunchoi

**Comment by sungeunchoi** [comment]
Do we actually need to update our minor version?  We haven't changed anything that make things incompatible, have we?

**Comment by hppritcha** [comment]
I think you're right.  I'll close this issue.
