### ISSUE TITLE
need to check whether GNI provider can work under CCM

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#94]
Need to verify that GNI provider can work under CCM.  May need to use CCM specific methods for getting ptag and cookie.

Need to find out if machines running srun can also run CCM.

Assigning to Sung for investigation

**Comment by hppritcha** [comment]
It appears this might be useful for Intel MPI on NERSC, etc. systems.  Setting label for 1.3 release milestone.

**Comment by sungeunchoi** [comment]
The answer is yes.  Opening new issue for the work.
