### ISSUE TITLE
fi_ext_gni.h cannot be included by C++

### ISSUE THREAD

**Issue by sdvormwa** [ofi-cray/libfabric-cray#949]
Looks like two problems.  First, the extern "C" block is never closed at the end of the file, leading to errors like

error: template with C linkage
error: expected '}' at end of input

Second, C-style forward declaration of enums doesn't work in C++, causing errors like

error: use of enum 'gnix_fab_req_type' without previous declaration
 enum gnix_fab_req_type;
      ^~~~~~~~~~~~~~~~~
error: use of enum 'gnix_fab_req_type' without previous declaration
         enum gnix_fab_req_type req_type,
              ^~~~~~~~~~~~~~~~~

**Comment by jswaro** [comment]
The second issue is duplicated by #956
