### ISSUE TITLE
Using FI_MULTI_RECV, all message receive completions have the FI_MULTI_RECV flag set.

### ISSUE THREAD

**Issue by epaulson10** [ofi-cray/libfabric-cray#965]
Hi, I am the newest member of Intel's OFI team and I am working on the GASNet OFI conduit, at the moment getting it working on the GNI.

The conduit currently uses FI_MULTI_RECV for its messaging. When using the GNI provider, I have noticed that the completion flags returned from the completion queue for received messages always have the FI_MULTI_RECV flag set. This flag is meant to alert you that the buffer has been used up although in this case the flag is coming back every time even though the buffer is sufficiently large. This is leading to strange issues in the conduit as it attempts to repost the buffer even though it is not yet consumed.

**Comment by sungeunchoi** [comment]
Related to #876.

**Comment by hppritcha** [comment]
Unfortunately the `FI_MULTI_RECV` feature seems to have a number of problems besides just the incorrect generation of `FI_MULTI_RECV` in the CQE.   This may not get fixed in time for 1.4 release.
