### ISSUE TITLE
Properly update man page for memory registration stuff

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#974]
The actual man page was updated, rather than fi_gni.7.md.

**Comment by sungeunchoi** [comment]
The changes that need to make it here are from #933 and #970

**Comment by jswaro** [comment]
I had originally modified the *.md files, but those weren't being used to create/install the man pages that were actually distributed. Is there a step I missed in the process?

**Comment by sungeunchoi** [comment]
It's a bit confusing, but see the README.  A bot turns the .md files into the man page.  The README also suggests a way to debug your changes to the .md files.

**Comment by jswaro** [comment]
How are you testing this locally? The GNI provider won't build without uGNI, and the fi_gni markdown doesn't appear to get processed unless the gni provider is being built.

**Comment by sungeunchoi** [comment]
Did you read the README?  I just did what it said and did "make nroff".  It's going to regenerate all the man pages, but you don't commit those.  Just the .md file.

**Comment by jswaro** [comment]
I did read the README. Can you verify this process works on your machine, because it does not work on mine without modifying the prov/gni/Makefile.include file to work around the issue to generate the new fi_gni.7 file.
