### ISSUE TITLE
need large page slab allocator that registers memory against gnix_nic's

### ISSUE THREAD

**Issue by hppritcha** [ofi-cray/libfabric-cray#98]
In order to efficiently use the Aries hardware for the GNI SMSG mailboxes, the GNI provider will need a slab allocator which allocates chunks of large pages to be dolled out to the provider as it needs memory for GNI SMSG mailboxes.  The chunks of large pages will need to be registered with one of the `gni_nic` structures associated with domain that had been used to create the EP which is using the SMSG mailboxes.  The chunks should be mmap'd with the MAP_SHARED to reduce COW issues if the application does subsequent forks. Part of solution for issue #5.

**Comment by bturrubiates** [comment]
Completed with #133.
