### ISSUE TITLE
Using FI_WAIT_UNSPEC for cq results in hang behavior in write()

### ISSUE THREAD

**Issue by agontarek** [ofi-cray/libfabric-cray#994]
If `FI_WAIT_UNSPEC` is used as a cq wait object, hang behavior can be observed in write(). This impacts applications issuing thousands of network operations that generate completions to the cq.

The manpage suggests that `FI_WAIT_UNSPEC` allows the provider to choose the optimal wait object:

> FI_WAIT_UNSPEC
> Specifies that the user will only wait on the CQ using fabric interface calls, such as fi_cq_sread or fi_cq_sreadfrom. In this case, the underlying provider may select the most appropriate or highest performing wait object available, including custom wait mechanisms. Applications that select FI_WAIT_UNSPEC are not guaranteed to retrieve the underlying wait object.

Also the manpage states that in order to use the blocking variants of the read calls (`fi_cq_sread` or `fi_cq_sreadfrom`) a wait object must be specified:

> FI_WAIT_NONE
> Used to indicate that the user will not block (wait) for completions on the CQ. When FI_WAIT_NONE is specified, the application may not call fi_cq_sread or fi_cq_sreadfrom.

In the gni provider code, a socket pair is created for the underlying FI_WAIT_UNSPEC wait object:

```
200     case FI_WAIT_FD:
201         if (socketpair(AF_LOCAL, SOCK_STREAM, 0, wait->fd))
202             goto err;
```

When a completion is generated, `_gnix_cq_add_event` calls `_gnix_signal_wait_obj` on the underlying wait obj:

```
142 void _gnix_signal_wait_obj(struct fid_wait *wait)
143 {
144     static char msg = 'g';
145     size_t len = sizeof(msg);
146     struct gnix_fid_wait *wait_priv;
147
148     wait_priv = container_of(wait, struct gnix_fid_wait, wait);
149
150     switch (wait_priv->type) {
151     case FI_WAIT_FD:
152         if (write(wait_priv->fd[WAIT_WRITE], &msg, len) != len)
153             GNIX_WARN(WAIT_SUB, "failed to signal wait object.\n");
154         break;
```

This writes a char to the write end of the socket. But at no point during `fi_cq_sread` is the char read from the read end of the socket. After enough network operations that generate completions to the cq, the recv buffer will fill up and the call to `write` will hang.

**Comment by hppritcha** [comment]
related to #981 in that `FI_WAIT_UNSPEC` for GNI provider is broken.

**Comment by ztiffany** [comment]
@agontarek do you mind if we return an error if anything but FI_WAIT_NONE is used?  We don't have wait sets implemented yet.  fi_cq_sread() is actually a busy spin wait regardless of the wait type requested.  That was implemented so we could run more tests.

**Comment by agontarek** [comment]
That solution is fine with me. My main concern here is that someone else porting to the gni provider might run into the same problem.

**Comment by jswaro** [comment]
I share the same concern as @agontarek , with respect to deviating from expected responses of the API.   

If wait sets aren't implemented, then why aren't we returning FI_ENOSYS?
