### ISSUE TITLE
Investigate fi_getinfo_test failure in fabtests

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/libfabric-cray#998]

**Comment by sungeunchoi** [comment]
We are failing this test because we do not fill in the src_addr field correctly on output.  From the man page:

"On output a provider shall return an address that corresponds to the indicated fabric or domain, with the format indicated by the returned addr_format field."

We only fill in src_addr if a node name is specified _and_ FI_SOURCE flag is set.  The second part is completely wrong (FI_SOURCE has nothing to do with specifying the source address).

@hppritcha You have comments in there about it not being complete.  Can you take a look?

**Comment by hppritcha** [comment]
fix in the works...

**Comment by sungeunchoi** [comment]
FYI since you didn't address my comment above, the FI_SOURCE confusion is already documented in https://github.com/ofiwg/libfabric/issues/2334.
